namespace Lace.Domain.DataProviders.Lightstone.Services
{
    public enum MetricTypes
    {
        None = 0,
        AmortisationFactors = 1,
        AreaFactors = 2,
        AuctionFactors = 3,
        AccidentDistribution = 4,
        RepairIndex = 5,
        TotalSalesByAge = 6,
        TotalSalesByGender = 7,
        RetailPriceNew = 8,
        RetailPriceLow = 9,
        RetailPriceHigh = 10,
        RetailEstimatedPrice = 11,
        Frequency = 12,
        RetailConfidence = 13,
        AmortisedValues = 14,
        AmortisedValuesMarketAverage = 15,
        NewVehicleSalesAveragePrice = 16,
        NewVehicleSalesNumberSold = 17,
        UsedVehicleSalesAveragePrice = 18,
        UsedVehicleSalesNumberSold = 19,
        SecurityIndex = 20,
        ResidualValue = 21,
        RepairCostIndex = 22,
        MaxSpeed = 23,
        Acceleration = 24,
        KiloWatts = 25,
        Torque = 26,
        FuelEconomy = 27,
        Co2 = 28,
        TotalCostOfParts = 29,
        TradeEstimatedPrice = 37,
        TradePriceLow = 35,
        TradePriceHigh = 36,
        TradeConfidence = 38,
        RetailAdjustment = 43,
        TradeAdjustment = 44
    }
}
