//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightstoneApp.Application.PackageBuilderModule.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightstoneApp.Application.PackageBuilderModule.Resx.ApplicationResources", typeof(ApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CostOfSale.
        /// </summary>
        public static string DataFieldCostOfSale {
            get {
                return ResourceManager.GetString("DataFieldCostOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataProviderId.
        /// </summary>
        public static string DataFieldDataProviderId {
            get {
                return ResourceManager.GetString("DataFieldDataProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string DataFieldId {
            get {
                return ResourceManager.GetString("DataFieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndustryId.
        /// </summary>
        public static string DataFieldIndustryId {
            get {
                return ResourceManager.GetString("DataFieldIndustryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string DataFieldLabel {
            get {
                return ResourceManager.GetString("DataFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DataFieldName {
            get {
                return ResourceManager.GetString("DataFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string DataFieldSelected {
            get {
                return ResourceManager.GetString("DataFieldSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeDefinition.
        /// </summary>
        public static string DataFieldTypeDefinition {
            get {
                return ResourceManager.GetString("DataFieldTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CostOfSale.
        /// </summary>
        public static string DataProviderCostOfSale {
            get {
                return ResourceManager.GetString("DataProviderCostOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string DataProviderCreated {
            get {
                return ResourceManager.GetString("DataProviderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DataProviderDescription {
            get {
                return ResourceManager.GetString("DataProviderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited.
        /// </summary>
        public static string DataProviderEdited {
            get {
                return ResourceManager.GetString("DataProviderEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string DataProviderId {
            get {
                return ResourceManager.GetString("DataProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DataProviderName {
            get {
                return ResourceManager.GetString("DataProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverrideFieldLevelCostOfSale.
        /// </summary>
        public static string DataProviderOverrideFieldLevelCostOfSale {
            get {
                return ResourceManager.GetString("DataProviderOverrideFieldLevelCostOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string DataProviderOwner {
            get {
                return ResourceManager.GetString("DataProviderOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RevisionDate.
        /// </summary>
        public static string DataProviderRevisionDate {
            get {
                return ResourceManager.GetString("DataProviderRevisionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceURL.
        /// </summary>
        public static string DataProviderSourceURL {
            get {
                return ResourceManager.GetString("DataProviderSourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateId.
        /// </summary>
        public static string DataProviderStateId {
            get {
                return ResourceManager.GetString("DataProviderStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string DataProviderVersion {
            get {
                return ResourceManager.GetString("DataProviderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Repository.
        /// </summary>
        public static string exception_WithoutRepository {
            get {
                return ResourceManager.GetString("exception_WithoutRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string IndustryId {
            get {
                return ResourceManager.GetString("IndustryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string IndustryValue {
            get {
                return ResourceManager.GetString("IndustryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CostOfSale.
        /// </summary>
        public static string PackageCostOfSale {
            get {
                return ResourceManager.GetString("PackageCostOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string PackageCreated {
            get {
                return ResourceManager.GetString("PackageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFieldId.
        /// </summary>
        public static string PackageDataFieldDataFieldId {
            get {
                return ResourceManager.GetString("PackageDataFieldDataFieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string PackageDataFieldId {
            get {
                return ResourceManager.GetString("PackageDataFieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageId.
        /// </summary>
        public static string PackageDataFieldPackageId {
            get {
                return ResourceManager.GetString("PackageDataFieldPackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string PackageDataFieldPriority {
            get {
                return ResourceManager.GetString("PackageDataFieldPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string PackageDataFieldSelected {
            get {
                return ResourceManager.GetString("PackageDataFieldSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnifiedName.
        /// </summary>
        public static string PackageDataFieldUnifiedName {
            get {
                return ResourceManager.GetString("PackageDataFieldUnifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PackageDescription {
            get {
                return ResourceManager.GetString("PackageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited.
        /// </summary>
        public static string PackageEdited {
            get {
                return ResourceManager.GetString("PackageEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string PackageId {
            get {
                return ResourceManager.GetString("PackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndustryId.
        /// </summary>
        public static string PackageIndustryId {
            get {
                return ResourceManager.GetString("PackageIndustryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PackageName {
            get {
                return ResourceManager.GetString("PackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string PackageOwner {
            get {
                return ResourceManager.GetString("PackageOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string PackagePublished {
            get {
                return ResourceManager.GetString("PackagePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecomendedRetailPrice.
        /// </summary>
        public static string PackageRecomendedRetailPrice {
            get {
                return ResourceManager.GetString("PackageRecomendedRetailPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RevisionDate.
        /// </summary>
        public static string PackageRevisionDate {
            get {
                return ResourceManager.GetString("PackageRevisionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateId.
        /// </summary>
        public static string PackageStateId {
            get {
                return ResourceManager.GetString("PackageStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string PackageVersion {
            get {
                return ResourceManager.GetString("PackageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string StateId {
            get {
                return ResourceManager.GetString("StateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string StateValue {
            get {
                return ResourceManager.GetString("StateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length exceeded [{1}].
        /// </summary>
        public static string validation_FieldMaxLenght {
            get {
                return ResourceManager.GetString("validation_FieldMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong range [{1} - {2}].
        /// </summary>
        public static string validation_FieldRange {
            get {
                return ResourceManager.GetString("validation_FieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string validation_FieldRequired {
            get {
                return ResourceManager.GetString("validation_FieldRequired", resourceCulture);
            }
        }
    }
}
