//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightstoneApp.Domain.PackageBuilderModule.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.PackageDataFields = new HashSet<PackageDataField>();
        }
    
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public System.Guid StateId { get; set; }
        public string Version { get; set; }
        public Nullable<decimal> CostOfSale { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Edited { get; set; }
        public Nullable<System.Guid> IndustryId { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<decimal> RecomendedRetailPrice { get; set; }
        public Nullable<System.DateTime> RevisionDate { get; set; }
    
        public virtual Industry Industry { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<PackageDataField> PackageDataFields { get; set; }
    }
}
