//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.PackageBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageDataField
    {
        public System.Guid Id { get; set; }
        public System.Guid DataFieldId { get; set; }
        public System.Guid PackageId { get; set; }
        public short Priority { get; set; }
        public bool Selected { get; set; }
        public string UnifiedName { get; set; }
    
        public virtual DataField DataField { get; set; }
        public virtual Package Package { get; set; }
    }
}
