//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.PackageBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.DataProviders = new HashSet<DataProvider>();
            this.Packages = new HashSet<Package>();
        }
    
        public System.Guid Id { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<DataProvider> DataProviders { get; set; }
        public virtual ICollection<Package> Packages { get; set; }
    }
}
