//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lace.Source.RgtVin.RgtVinServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.rgt.co.za/systems/", ConfigurationName="RgtVinServiceReference.wsVinCheckSoap")]
    public interface wsVinCheckSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rgt.co.za/systems/VinCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VinCheck(string sVIN, string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rgt.co.za/systems/VinCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<string> VinCheckAsync(string sVIN, string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rgt.co.za/systems/VinCheckAlt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VinCheckAlt(string sVIN, string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rgt.co.za/systems/VinCheckAlt", ReplyAction="*")]
        System.Threading.Tasks.Task<string> VinCheckAltAsync(string sVIN, string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rgt.co.za/systems/VinCheck_List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VinCheck_List(string sVIN, string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rgt.co.za/systems/VinCheck_List", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> VinCheck_ListAsync(string sVIN, string sCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsVinCheckSoapChannel : Lace.Source.RgtVin.RgtVinServiceReference.wsVinCheckSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsVinCheckSoapClient : System.ServiceModel.ClientBase<Lace.Source.RgtVin.RgtVinServiceReference.wsVinCheckSoap>, Lace.Source.RgtVin.RgtVinServiceReference.wsVinCheckSoap {
        
        public wsVinCheckSoapClient() {
        }
        
        public wsVinCheckSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsVinCheckSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsVinCheckSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsVinCheckSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string VinCheck(string sVIN, string sCode) {
            return base.Channel.VinCheck(sVIN, sCode);
        }
        
        public System.Threading.Tasks.Task<string> VinCheckAsync(string sVIN, string sCode) {
            return base.Channel.VinCheckAsync(sVIN, sCode);
        }
        
        public string VinCheckAlt(string sVIN, string sCode) {
            return base.Channel.VinCheckAlt(sVIN, sCode);
        }
        
        public System.Threading.Tasks.Task<string> VinCheckAltAsync(string sVIN, string sCode) {
            return base.Channel.VinCheckAltAsync(sVIN, sCode);
        }
        
        public System.Data.DataSet VinCheck_List(string sVIN, string sCode) {
            return base.Channel.VinCheck_List(sVIN, sCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> VinCheck_ListAsync(string sVIN, string sCode) {
            return base.Channel.VinCheck_ListAsync(sVIN, sCode);
        }
    }
}
