//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lace.Source.Audatex.AudatexServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CredentialsInfo", Namespace="http://www.audatex.co.uk/Enterprise")]
    [System.SerializableAttribute()]
    public partial class CredentialsInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDataResult", Namespace="http://www.audatex.co.uk/Enterprise")]
    [System.SerializableAttribute()]
    public partial class GetDataResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        private int MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeIdentifierField;
        
        private int QueueDepthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageEnvelopeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((this.MessageIdField.Equals(value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageTypeIdentifier {
            get {
                return this.MessageTypeIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeIdentifierField, value) != true)) {
                    this.MessageTypeIdentifierField = value;
                    this.RaisePropertyChanged("MessageTypeIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int QueueDepth {
            get {
                return this.QueueDepthField;
            }
            set {
                if ((this.QueueDepthField.Equals(value) != true)) {
                    this.QueueDepthField = value;
                    this.RaisePropertyChanged("QueueDepth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MessageEnvelope {
            get {
                return this.MessageEnvelopeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageEnvelopeField, value) != true)) {
                    this.MessageEnvelopeField = value;
                    this.RaisePropertyChanged("MessageEnvelope");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AdditionalInfo {
            get {
                return this.AdditionalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInfoField, value) != true)) {
                    this.AdditionalInfoField = value;
                    this.RaisePropertyChanged("AdditionalInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PutDataResult", Namespace="http://www.audatex.co.uk/Enterprise")]
    [System.SerializableAttribute()]
    public partial class PutDataResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AdditionalData {
            get {
                return this.AdditionalDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalDataField, value) != true)) {
                    this.AdditionalDataField = value;
                    this.RaisePropertyChanged("AdditionalData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.audatex.co.uk/Enterprise", ConfigurationName="AudatexServiceReference.BackOfficeWebServiceSoap")]
    public interface BackOfficeWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name Credentials from namespace http://www.audatex.co.uk/Enterprise is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.audatex.co.uk/Enterprise/GetDataEx", ReplyAction="*")]
        Lace.Source.Audatex.AudatexServiceReference.GetDataExResponse GetDataEx(Lace.Source.Audatex.AudatexServiceReference.GetDataExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.audatex.co.uk/Enterprise/GetDataEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Lace.Source.Audatex.AudatexServiceReference.GetDataExResponse> GetDataExAsync(Lace.Source.Audatex.AudatexServiceReference.GetDataExRequest request);
        
        // CODEGEN: Generating message contract since element name Credentials from namespace http://www.audatex.co.uk/Enterprise is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.audatex.co.uk/Enterprise/GetData", ReplyAction="*")]
        Lace.Source.Audatex.AudatexServiceReference.GetDataResponse GetData(Lace.Source.Audatex.AudatexServiceReference.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.audatex.co.uk/Enterprise/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<Lace.Source.Audatex.AudatexServiceReference.GetDataResponse> GetDataAsync(Lace.Source.Audatex.AudatexServiceReference.GetDataRequest request);
        
        // CODEGEN: Generating message contract since element name Credentials from namespace http://www.audatex.co.uk/Enterprise is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.audatex.co.uk/Enterprise/PutData", ReplyAction="*")]
        Lace.Source.Audatex.AudatexServiceReference.PutDataResponse PutData(Lace.Source.Audatex.AudatexServiceReference.PutDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.audatex.co.uk/Enterprise/PutData", ReplyAction="*")]
        System.Threading.Tasks.Task<Lace.Source.Audatex.AudatexServiceReference.PutDataResponse> PutDataAsync(Lace.Source.Audatex.AudatexServiceReference.PutDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataEx", Namespace="http://www.audatex.co.uk/Enterprise", Order=0)]
        public Lace.Source.Audatex.AudatexServiceReference.GetDataExRequestBody Body;
        
        public GetDataExRequest() {
        }
        
        public GetDataExRequest(Lace.Source.Audatex.AudatexServiceReference.GetDataExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.audatex.co.uk/Enterprise")]
    public partial class GetDataExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lace.Source.Audatex.AudatexServiceReference.CredentialsInfo Credentials;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageTypeIdentifier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MessageEnvelope;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int MessageAckId;
        
        public GetDataExRequestBody() {
        }
        
        public GetDataExRequestBody(Lace.Source.Audatex.AudatexServiceReference.CredentialsInfo Credentials, string MessageTypeIdentifier, string MessageEnvelope, int MessageAckId) {
            this.Credentials = Credentials;
            this.MessageTypeIdentifier = MessageTypeIdentifier;
            this.MessageEnvelope = MessageEnvelope;
            this.MessageAckId = MessageAckId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataExResponse", Namespace="http://www.audatex.co.uk/Enterprise", Order=0)]
        public Lace.Source.Audatex.AudatexServiceReference.GetDataExResponseBody Body;
        
        public GetDataExResponse() {
        }
        
        public GetDataExResponse(Lace.Source.Audatex.AudatexServiceReference.GetDataExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.audatex.co.uk/Enterprise")]
    public partial class GetDataExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lace.Source.Audatex.AudatexServiceReference.GetDataResult GetDataExResult;
        
        public GetDataExResponseBody() {
        }
        
        public GetDataExResponseBody(Lace.Source.Audatex.AudatexServiceReference.GetDataResult GetDataExResult) {
            this.GetDataExResult = GetDataExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://www.audatex.co.uk/Enterprise", Order=0)]
        public Lace.Source.Audatex.AudatexServiceReference.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(Lace.Source.Audatex.AudatexServiceReference.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.audatex.co.uk/Enterprise")]
    public partial class GetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lace.Source.Audatex.AudatexServiceReference.CredentialsInfo Credentials;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageTypeIdentifier;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int MessageAckId;
        
        public GetDataRequestBody() {
        }
        
        public GetDataRequestBody(Lace.Source.Audatex.AudatexServiceReference.CredentialsInfo Credentials, string MessageTypeIdentifier, int MessageAckId) {
            this.Credentials = Credentials;
            this.MessageTypeIdentifier = MessageTypeIdentifier;
            this.MessageAckId = MessageAckId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://www.audatex.co.uk/Enterprise", Order=0)]
        public Lace.Source.Audatex.AudatexServiceReference.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(Lace.Source.Audatex.AudatexServiceReference.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.audatex.co.uk/Enterprise")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lace.Source.Audatex.AudatexServiceReference.GetDataResult GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(Lace.Source.Audatex.AudatexServiceReference.GetDataResult GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutData", Namespace="http://www.audatex.co.uk/Enterprise", Order=0)]
        public Lace.Source.Audatex.AudatexServiceReference.PutDataRequestBody Body;
        
        public PutDataRequest() {
        }
        
        public PutDataRequest(Lace.Source.Audatex.AudatexServiceReference.PutDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.audatex.co.uk/Enterprise")]
    public partial class PutDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lace.Source.Audatex.AudatexServiceReference.CredentialsInfo Credentials;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageTypeIdenfitier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MessageEnvelope;
        
        public PutDataRequestBody() {
        }
        
        public PutDataRequestBody(Lace.Source.Audatex.AudatexServiceReference.CredentialsInfo Credentials, string MessageTypeIdenfitier, string MessageEnvelope) {
            this.Credentials = Credentials;
            this.MessageTypeIdenfitier = MessageTypeIdenfitier;
            this.MessageEnvelope = MessageEnvelope;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutDataResponse", Namespace="http://www.audatex.co.uk/Enterprise", Order=0)]
        public Lace.Source.Audatex.AudatexServiceReference.PutDataResponseBody Body;
        
        public PutDataResponse() {
        }
        
        public PutDataResponse(Lace.Source.Audatex.AudatexServiceReference.PutDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.audatex.co.uk/Enterprise")]
    public partial class PutDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lace.Source.Audatex.AudatexServiceReference.PutDataResult PutDataResult;
        
        public PutDataResponseBody() {
        }
        
        public PutDataResponseBody(Lace.Source.Audatex.AudatexServiceReference.PutDataResult PutDataResult) {
            this.PutDataResult = PutDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BackOfficeWebServiceSoapChannel : Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BackOfficeWebServiceSoapClient : System.ServiceModel.ClientBase<Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap>, Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap {
        
        public BackOfficeWebServiceSoapClient() {
        }
        
        public BackOfficeWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BackOfficeWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackOfficeWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackOfficeWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lace.Source.Audatex.AudatexServiceReference.GetDataExResponse Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap.GetDataEx(Lace.Source.Audatex.AudatexServiceReference.GetDataExRequest request) {
            return base.Channel.GetDataEx(request);
        }
        
        public Lace.Source.Audatex.AudatexServiceReference.GetDataResult GetDataEx(Lace.Source.Audatex.AudatexServiceReference.CredentialsInfo Credentials, string MessageTypeIdentifier, string MessageEnvelope, int MessageAckId) {
            Lace.Source.Audatex.AudatexServiceReference.GetDataExRequest inValue = new Lace.Source.Audatex.AudatexServiceReference.GetDataExRequest();
            inValue.Body = new Lace.Source.Audatex.AudatexServiceReference.GetDataExRequestBody();
            inValue.Body.Credentials = Credentials;
            inValue.Body.MessageTypeIdentifier = MessageTypeIdentifier;
            inValue.Body.MessageEnvelope = MessageEnvelope;
            inValue.Body.MessageAckId = MessageAckId;
            Lace.Source.Audatex.AudatexServiceReference.GetDataExResponse retVal = ((Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap)(this)).GetDataEx(inValue);
            return retVal.Body.GetDataExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lace.Source.Audatex.AudatexServiceReference.GetDataExResponse> Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap.GetDataExAsync(Lace.Source.Audatex.AudatexServiceReference.GetDataExRequest request) {
            return base.Channel.GetDataExAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lace.Source.Audatex.AudatexServiceReference.GetDataExResponse> GetDataExAsync(Lace.Source.Audatex.AudatexServiceReference.CredentialsInfo Credentials, string MessageTypeIdentifier, string MessageEnvelope, int MessageAckId) {
            Lace.Source.Audatex.AudatexServiceReference.GetDataExRequest inValue = new Lace.Source.Audatex.AudatexServiceReference.GetDataExRequest();
            inValue.Body = new Lace.Source.Audatex.AudatexServiceReference.GetDataExRequestBody();
            inValue.Body.Credentials = Credentials;
            inValue.Body.MessageTypeIdentifier = MessageTypeIdentifier;
            inValue.Body.MessageEnvelope = MessageEnvelope;
            inValue.Body.MessageAckId = MessageAckId;
            return ((Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap)(this)).GetDataExAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lace.Source.Audatex.AudatexServiceReference.GetDataResponse Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap.GetData(Lace.Source.Audatex.AudatexServiceReference.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public Lace.Source.Audatex.AudatexServiceReference.GetDataResult GetData(Lace.Source.Audatex.AudatexServiceReference.CredentialsInfo Credentials, string MessageTypeIdentifier, int MessageAckId) {
            Lace.Source.Audatex.AudatexServiceReference.GetDataRequest inValue = new Lace.Source.Audatex.AudatexServiceReference.GetDataRequest();
            inValue.Body = new Lace.Source.Audatex.AudatexServiceReference.GetDataRequestBody();
            inValue.Body.Credentials = Credentials;
            inValue.Body.MessageTypeIdentifier = MessageTypeIdentifier;
            inValue.Body.MessageAckId = MessageAckId;
            Lace.Source.Audatex.AudatexServiceReference.GetDataResponse retVal = ((Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap)(this)).GetData(inValue);
            return retVal.Body.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lace.Source.Audatex.AudatexServiceReference.GetDataResponse> Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap.GetDataAsync(Lace.Source.Audatex.AudatexServiceReference.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lace.Source.Audatex.AudatexServiceReference.GetDataResponse> GetDataAsync(Lace.Source.Audatex.AudatexServiceReference.CredentialsInfo Credentials, string MessageTypeIdentifier, int MessageAckId) {
            Lace.Source.Audatex.AudatexServiceReference.GetDataRequest inValue = new Lace.Source.Audatex.AudatexServiceReference.GetDataRequest();
            inValue.Body = new Lace.Source.Audatex.AudatexServiceReference.GetDataRequestBody();
            inValue.Body.Credentials = Credentials;
            inValue.Body.MessageTypeIdentifier = MessageTypeIdentifier;
            inValue.Body.MessageAckId = MessageAckId;
            return ((Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap)(this)).GetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lace.Source.Audatex.AudatexServiceReference.PutDataResponse Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap.PutData(Lace.Source.Audatex.AudatexServiceReference.PutDataRequest request) {
            return base.Channel.PutData(request);
        }
        
        public Lace.Source.Audatex.AudatexServiceReference.PutDataResult PutData(Lace.Source.Audatex.AudatexServiceReference.CredentialsInfo Credentials, string MessageTypeIdenfitier, string MessageEnvelope) {
            Lace.Source.Audatex.AudatexServiceReference.PutDataRequest inValue = new Lace.Source.Audatex.AudatexServiceReference.PutDataRequest();
            inValue.Body = new Lace.Source.Audatex.AudatexServiceReference.PutDataRequestBody();
            inValue.Body.Credentials = Credentials;
            inValue.Body.MessageTypeIdenfitier = MessageTypeIdenfitier;
            inValue.Body.MessageEnvelope = MessageEnvelope;
            Lace.Source.Audatex.AudatexServiceReference.PutDataResponse retVal = ((Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap)(this)).PutData(inValue);
            return retVal.Body.PutDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lace.Source.Audatex.AudatexServiceReference.PutDataResponse> Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap.PutDataAsync(Lace.Source.Audatex.AudatexServiceReference.PutDataRequest request) {
            return base.Channel.PutDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lace.Source.Audatex.AudatexServiceReference.PutDataResponse> PutDataAsync(Lace.Source.Audatex.AudatexServiceReference.CredentialsInfo Credentials, string MessageTypeIdenfitier, string MessageEnvelope) {
            Lace.Source.Audatex.AudatexServiceReference.PutDataRequest inValue = new Lace.Source.Audatex.AudatexServiceReference.PutDataRequest();
            inValue.Body = new Lace.Source.Audatex.AudatexServiceReference.PutDataRequestBody();
            inValue.Body.Credentials = Credentials;
            inValue.Body.MessageTypeIdenfitier = MessageTypeIdenfitier;
            inValue.Body.MessageEnvelope = MessageEnvelope;
            return ((Lace.Source.Audatex.AudatexServiceReference.BackOfficeWebServiceSoap)(this)).PutDataAsync(inValue);
        }
    }
}
