//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LightstoneApp.Domain.PackageBuilderModule.Entities;

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;



using LightstoneApp.Infrastructure.Data.Core;


namespace LightstoneApp.Infrastructure.Data.PackageBuilder.UnitOfWork
{
    
    ///<sumary>
    ///Base contract for context in Package Builder Module 
    ///</sumary>
    public interface IPackageBuilderUnitOfWork :IQueryableUnitOfWork
    {
       
        #region ObjectSet Properties
    
        IObjectSet<DataSource> DataSources{get;}
        
    
        IObjectSet<DateField> DateFields{get;}
        
    
        IObjectSet<FileAttachment> FileAttachments{get;}
        
    
        IObjectSet<Industry> Industries{get;}
        
    
        IObjectSet<Owner> Owners{get;}
        
    
        IObjectSet<Package> Packages{get;}
        
    
        IObjectSet<State> States{get;}
        

        #endregion

    
    }
}
	
