//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lace.Domain.DataProviders.Lightstone.Business.Director.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://test.lightstonebusiness.co.za/lsb/api/api.asmx")]
        public string Lightstone_DataPlatform_Lace_Domain_DataProviders_Lightstone_Lace_Domain_DataProviders_Lightstone_Business_Director_LightstoneBusinessServiceReference1_api {
            get {
                return ((string)(this["Lightstone_DataPlatform_Lace_Domain_DataProviders_Lightstone_Lace_Domain_DataProv" +
                    "iders_Lightstone_Business_Director_LightstoneBusinessServiceReference1_api"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://test.lightstonebusiness.co.za/lsb/api/api.asmx")]
        public string Lightstone_DataPlatform_Lace_Domain_DataProviders_Lightstone_Lace_Domain_DataProviders_Lightstone_Business_Director_LightstoneBusinessServiceReference_api {
            get {
                return ((string)(this["Lightstone_DataPlatform_Lace_Domain_DataProviders_Lightstone_Lace_Domain_DataProv" +
                    "iders_Lightstone_Business_Director_LightstoneBusinessServiceReference_api"]));
            }
        }
    }
}
