using System.Dynamic;

namespace Lace.Domain.Core.Contracts.Requests
{
    /// <summary>
    /// ReturnProperties Input Data
    /// </summary>
    public interface IProvidePropertyInformationForRequest
    {

        /// <summary>
        /// Is a unique sequence of characters that is given to a user of the system and this is used to identify that user.

        /// </summary>
        string User_ID { get; set; }


        /// <summary>
        /// "PROV_ID:PROVINCE:PROVINCE_ABBREV
        /// 1 LIMPOPO LIM
        /// 2 FREE STATE FS
        /// 3 NORTHERN CAPE NC
        /// 4 WESTERN CAPE WC
        /// 5 KWAZULU NATAL KN
        /// 6 MPUMALANGA MP
        /// 7 NORTH WEST NW
        /// 8 GAUTENG GA
        /// 9 EASTERN CAPE EC
        /// 10 FARMS FR
        /// </summary>
        string Province { get; set; }

        /// <summary>
        /// This is the textual description of the municipality name that the property resides in.
        /// </summary>
        string Municipality { get; set; }

        /// <summary>
        /// This is the textual description of the Deedtown name that the property resides in.
        /// </summary>
        string DeedTown { get; set; }

        /// <summary>
        /// This field contains the erf number of the property.
        /// </summary>
        string Erf { get; set; }
        
        /// <summary>
        /// This field contains the portion number of the property.
        /// </summary>
        string Portion { get; set; }

        /// <summary>
        /// This is the textual description of the Sectional Title scheme name that the property resides in.
        /// </summary>
        string Sectional_Title { get; set; }

        /// <summary>
        /// This is the suburb name that the property is registered in 
        /// </summary>
        string Suburb { get; set; }

        

        /// <summary>
        /// This field contains the street name of the property.
        /// </summary>
        string Street { get; set; }

        
        /// <summary>
        /// This field contains the name of the owner of the property.
        /// </summary>
        string Owner_Name { get; set; }

        /// <summary>
        /// ID number of the property owner if a natural person or Company Registration number of property owners if Legal Entity
        /// </summary>
        string ID_CK { get; set; }

        
        /// <summary>
        /// This is the name of the Estate that the property is located in
        /// </summary>
        string Estate_Name { get; set; }

        /// <summary>
        /// This is the name of the farm if the property returned is a farm.
        /// </summary>
        string FARM_NAME { get; set; }

        /// <summary>
        /// This field is mandatory and denotes the Max Number of results to return - it's advised to limit this to make the resulting data set smaller to download
        /// </summary>
        int MaxRowsToReturn { get; set; }

        /// <summary>
        /// This field is and internal tracking number generated by the requesting company and is used to track reports between Lightstone and "the client" for billing purposes.
        /// </summary>
        string TrackingNumber { get; set; }




    }
}
