namespace Workflow.Reporting.Entities
{
    public class ReportPastelNewCustomer
    {
        public string DCLink { get; set; } 
        public string AccountID { get; set; } 
        public string Name { get; set; } 
        public string Title { get; set; } 
        public string Init { get; set; } 
        public string Contact_Person { get; set; } 
        public string Physical1 { get; set; } 
        public string Physical2 { get; set; } 
        public string Physical3 { get; set; } 
        public string Physical4 { get; set; } 
        public string Physical5 { get; set; } 
        public string PhysicalPC { get; set; } 
        public string Addressee { get; set; } 
        public string Post1 { get; set; } 
        public string Post2 { get; set; } 
        public string Post3 { get; set; } 
        public string Post4 { get; set; } 
        public string Post5 { get; set; } 
        public string PostPC { get; set; } 
        public string Delivered_To { get; set; } 
        public string Telephone { get; set; } 
        public string Telephone2 { get; set; } 
        public string Fax1 { get; set; } 
        public string Fax2 { get; set; } 
        public string iClassID { get; set; } 
        public string AccountTerms { get; set; } 
        public string CT { get; set; } 
        public string Tax_Number { get; set; } 
        public string Registration { get; set; } 
        public string iAreasID { get; set; } 
        public string Credit_Limit { get; set; } 
        public string Interest_Rate { get; set; } 
        public string Discount { get; set; } 
        public string On_Hold { get; set; } 
        public string BFOpenType { get; set; } 
        public string EMail { get; set; } 
        public string BankLink { get; set; } 
        public string BranchCode { get; set; } 
        public string BankAccNum { get; set; } 
        public string BankAccType { get; set; } 
        public string AutoDisc { get; set; } 
        public string DiscMtrxRow { get; set; } 
        public string CheckTerms { get; set; } 
        public string UseEmail { get; set; } 
        public string dTimeStamp { get; set; } 
        public string cAccDescription { get; set; } 
        public string cWebPage { get; set; } 
        public string cBankRefNr { get; set; } 
        public string iCurrencyID { get; set; } 
        public string bStatPrint { get; set; } 
        public string bStatEmail { get; set; } 
        public string cStatEmailPass { get; set; } 
        public string bForCurAcc { get; set; } 
        public string iSettlementTermsID { get; set; } 
        public string iEUCountryID { get; set; } 
        public string iDefTaxTypeID { get; set; } 
        public string RepID { get; set; } 
        public string MainAccLink { get; set; } 
        public string CashDebtor { get; set; } 
        public string iIncidentTypeID { get; set; } 
        public string iBusTypeID { get; set; } 
        public string iBusClassID { get; set; } 
        public string iAgentID { get; set; } 
        public string bTaxPrompt { get; set; } 
        public string iARPriceListNameID { get; set; } 
        public string bCODAccount { get; set; }
    }
}