//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18449.
// 
#pragma warning disable 1591

namespace Lace.Source.Anpr.AnprServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AnprServiceSoap", Namespace="http://localhost")]
    public partial class AnprService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AnprProcessRecognitionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AnprService() {
            this.Url = "http://adslskyhi.dyndns.org:88/AnprService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AnprProcessRecognitionCompletedEventHandler AnprProcessRecognitionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/AnprProcessRecognition", RequestNamespace="http://localhost", ResponseNamespace="http://localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AnprResComplexType AnprProcessRecognition(AnprSubComplexType aps) {
            object[] results = this.Invoke("AnprProcessRecognition", new object[] {
                        aps});
            return ((AnprResComplexType)(results[0]));
        }
        
        /// <remarks/>
        public void AnprProcessRecognitionAsync(AnprSubComplexType aps) {
            this.AnprProcessRecognitionAsync(aps, null);
        }
        
        /// <remarks/>
        public void AnprProcessRecognitionAsync(AnprSubComplexType aps, object userState) {
            if ((this.AnprProcessRecognitionOperationCompleted == null)) {
                this.AnprProcessRecognitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAnprProcessRecognitionOperationCompleted);
            }
            this.InvokeAsync("AnprProcessRecognition", new object[] {
                        aps}, this.AnprProcessRecognitionOperationCompleted, userState);
        }
        
        private void OnAnprProcessRecognitionOperationCompleted(object arg) {
            if ((this.AnprProcessRecognitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AnprProcessRecognitionCompleted(this, new AnprProcessRecognitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost")]
    public partial class AnprSubComplexType {
        
        private string imagetoAnprField;
        
        /// <remarks/>
        public string ImagetoAnpr {
            get {
                return this.imagetoAnprField;
            }
            set {
                this.imagetoAnprField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost")]
    public partial class AnprResComplexType {
        
        private string platePatchField;
        
        private string overviewField;
        
        private string plateResultField;
        
        private string resultField;
        
        private int confidenceField;
        
        /// <remarks/>
        public string PlatePatch {
            get {
                return this.platePatchField;
            }
            set {
                this.platePatchField = value;
            }
        }
        
        /// <remarks/>
        public string Overview {
            get {
                return this.overviewField;
            }
            set {
                this.overviewField = value;
            }
        }
        
        /// <remarks/>
        public string PlateResult {
            get {
                return this.plateResultField;
            }
            set {
                this.plateResultField = value;
            }
        }
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public int Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AnprProcessRecognitionCompletedEventHandler(object sender, AnprProcessRecognitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnprProcessRecognitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AnprProcessRecognitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AnprResComplexType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AnprResComplexType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591