//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lace.Domain.DataProviders.Lightstone.Property.LspServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LspServiceReference.PropertiesSoap")]
    public interface PropertiesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnProperties(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    int MaxRowsToReturn, 
                    string TrackingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnPropertiesAsync(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    int MaxRowsToReturn, 
                    string TrackingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties_Prop_ID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnProperties_Prop_ID(string User_ID, long prop_id, string TrackingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties_Prop_ID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnProperties_Prop_IDAsync(string User_ID, long prop_id, string TrackingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties_Alt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnProperties_Alt(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string StreetType, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    string Registrar, 
                    int MaxRowsToReturn, 
                    string TrackingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties_Alt", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnProperties_AltAsync(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string StreetType, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    string Registrar, 
                    int MaxRowsToReturn, 
                    string TrackingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties_Alt_Coords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnProperties_Alt_Coords(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string Street_Type, 
                    string Registrar, 
                    string FirstName, 
                    string SecondName, 
                    string Surname, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    int MaxRowsToReturn, 
                    string TrackingNumber, 
                    string x, 
                    string y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties_Alt_Coords", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnProperties_Alt_CoordsAsync(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string Street_Type, 
                    string Registrar, 
                    string FirstName, 
                    string SecondName, 
                    string Surname, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    int MaxRowsToReturn, 
                    string TrackingNumber, 
                    string x, 
                    string y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties_Crit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnProperties_Crit(Lace.Domain.DataProviders.Lightstone.Property.LspServiceReference.Property_Search_Criteria Criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties_Crit", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnProperties_CritAsync(Lace.Domain.DataProviders.Lightstone.Property.LspServiceReference.Property_Search_Criteria Criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties_SplitNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnProperties_SplitNames(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string StreetType, 
                    string FirstName, 
                    string SecondName, 
                    string Surname, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    string Registrar, 
                    int MaxRowsToReturn, 
                    string TrackingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties_SplitNames", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnProperties_SplitNamesAsync(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string StreetType, 
                    string FirstName, 
                    string SecondName, 
                    string Surname, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    string Registrar, 
                    int MaxRowsToReturn, 
                    string TrackingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties_ReqStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnProperties_ReqStatus(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string Street_Type, 
                    string StreetNumber, 
                    string StreetType, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    string Registrar, 
                    int MaxRowsToReturn, 
                    string TrackingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties_ReqStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnProperties_ReqStatusAsync(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string Street_Type, 
                    string StreetNumber, 
                    string StreetType, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    string Registrar, 
                    int MaxRowsToReturn, 
                    string TrackingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmValidation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConfirmValidation(string User_ID, string TrackingNumber, int Prop_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmValidation", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ConfirmValidationAsync(string User_ID, string TrackingNumber, int Prop_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnValuation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnValuation(string User_ID, string TrackingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnValuation", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnValuationAsync(string User_ID, string TrackingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnValuation_Banking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnValuation_Banking(string User_ID, string TrackingNumber, int PurchasePrice, int LoanAmount, bool Advance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnValuation_Banking", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnValuation_BankingAsync(string User_ID, string TrackingNumber, int PurchasePrice, int LoanAmount, bool Advance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnPropertyReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnPropertyReport(string User_ID, string TrackingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnPropertyReport", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnPropertyReportAsync(string User_ID, string TrackingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSuburbs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnSuburbs(string Suburb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSuburbs", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnSuburbsAsync(string Suburb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSuburb_Report_WithHistory_Sub_ID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnSuburb_Report_WithHistory_Sub_ID(string User_ID, int sub_id, string Trackingnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSuburb_Report_WithHistory_Sub_ID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnSuburb_Report_WithHistory_Sub_IDAsync(string User_ID, int sub_id, string Trackingnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSuburb_Report_WithHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnSuburb_Report_WithHistory(string User_ID, string suburb, string deed_id, string Trackingnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSuburb_Report_WithHistory", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnSuburb_Report_WithHistoryAsync(string User_ID, string suburb, string deed_id, string Trackingnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSuburb_Report", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnSuburb_Report(string User_ID, string suburb, string deed_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSuburb_Report", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnSuburb_ReportAsync(string User_ID, string suburb, string deed_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSuburb_Trends", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnSuburb_Trends(int sub_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSuburb_Trends", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnSuburb_TrendsAsync(int sub_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnTransfers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnTransfers(
                    string user_id, 
                    string Sectional_Title, 
                    string Street, 
                    string Suburb, 
                    string RegDateFrom, 
                    string RegDateTo, 
                    string SalesDateFrom, 
                    string SalesDateTo, 
                    string PriceFrom, 
                    string PriceTo, 
                    int PropType_ID, 
                    string Buyer_Name, 
                    string Deedtown, 
                    string Erf, 
                    string Portion, 
                    string farm, 
                    string ErfSizeFrom, 
                    string ErfSizeTo, 
                    string Estate, 
                    string Ext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnTransfers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnTransfersAsync(
                    string user_id, 
                    string Sectional_Title, 
                    string Street, 
                    string Suburb, 
                    string RegDateFrom, 
                    string RegDateTo, 
                    string SalesDateFrom, 
                    string SalesDateTo, 
                    string PriceFrom, 
                    string PriceTo, 
                    int PropType_ID, 
                    string Buyer_Name, 
                    string Deedtown, 
                    string Erf, 
                    string Portion, 
                    string farm, 
                    string ErfSizeFrom, 
                    string ErfSizeTo, 
                    string Estate, 
                    string Ext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnOwners", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnOwners(string User_ID, string Person_IDNumber, string Person_Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnOwners", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnOwnersAsync(string User_ID, string Person_IDNumber, string Person_Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnOwners_History", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnOwners_History(string User_ID, string IDNumbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnOwners_History", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnOwners_HistoryAsync(string User_ID, string IDNumbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSectionalSchemes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnSectionalSchemes(string Sectional_Scheme_name, string Sectional_Scheme_No);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSectionalSchemes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnSectionalSchemesAsync(string Sectional_Scheme_name, string Sectional_Scheme_No);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSectionalSchemeReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnSectionalSchemeReport(string user_id, int ss_group_id, string trackingnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSectionalSchemeReport", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnSectionalSchemeReportAsync(string user_id, int ss_group_id, string trackingnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnEstates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnEstates(string Estate_Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnEstates", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnEstatesAsync(string Estate_Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnEstateReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnEstateReport(string user_id, int Estate_ID, string trackingnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnEstateReport", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnEstateReportAsync(string user_id, int Estate_ID, string trackingnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnLegalEntities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnLegalEntities(string User_ID, string idnumber, string name, string firstname, string secondname, string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnLegalEntities", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnLegalEntitiesAsync(string User_ID, string idnumber, string name, string firstname, string secondname, string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnLegalEntitiyReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnLegalEntitiyReport(string User_ID, int le_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnLegalEntitiyReport", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnLegalEntitiyReportAsync(string User_ID, int le_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnHedonicFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet returnHedonicFields();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnHedonicFields", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> returnHedonicFieldsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishHedonicDataTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet publishHedonicDataTable(string reqprop_id, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishHedonicDataTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> publishHedonicDataTableAsync(string reqprop_id, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishHedonicData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string publishHedonicData(string reqprop_id, string fieldname, string fieldvalue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishHedonicData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> publishHedonicDataAsync(string reqprop_id, string fieldname, string fieldvalue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnOwnersInComplexReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet returnOwnersInComplexReport(string User_ID, int complexId, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnOwnersInComplexReport", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> returnOwnersInComplexReportAsync(string User_ID, int complexId, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnSGDiagramsReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet returnSGDiagramsReport(string User_ID, int office, int urbanRural, string town, int erf, int portion, string farm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnSGDiagramsReport", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> returnSGDiagramsReportAsync(string User_ID, int office, int urbanRural, string town, int erf, int portion, string farm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnQuickValuation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet returnQuickValuation(string User_ID, string ReqProp_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnQuickValuation", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> returnQuickValuationAsync(string User_ID, string ReqProp_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnTowns", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet returnTowns(string townname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnTowns", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> returnTownsAsync(string townname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnTownReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet returnTownReport(string user_id, int town_id, string trackingnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnTownReport", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> returnTownReportAsync(string user_id, int town_id, string trackingnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnTownReportFromID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet returnTownReportFromID(string tr_guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnTownReportFromID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> returnTownReportFromIDAsync(string tr_guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnPropertyInsuranceReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet returnPropertyInsuranceReport(int prop_id, string user_id, string trackingnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnPropertyInsuranceReport", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> returnPropertyInsuranceReportAsync(int prop_id, string user_id, string trackingnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnStreets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet returnStreets(int sub_id, string street_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnStreets", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> returnStreetsAsync(int sub_id, string street_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties_address", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnProperties_address(string user_id, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnProperties_address", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnProperties_addressAsync(string user_id, string address);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Property_Search_Criteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid user_idField;
        
        private string trackingnumerField;
        
        private int maxRowsField;
        
        private decimal prop_idField;
        
        private decimal prov_idField;
        
        private string provinceField;
        
        private int munic_idField;
        
        private string municipalityField;
        
        private string farmnameField;
        
        private decimal deed_idField;
        
        private string deedtownField;
        
        private string erfField;
        
        private string portionField;
        
        private decimal ss_idField;
        
        private string sectional_schemeField;
        
        private string sectional_scheme_noField;
        
        private string unitField;
        
        private int est_idField;
        
        private string estate_nameField;
        
        private string erf_keyField;
        
        private decimal proptype_idField;
        
        private string property_typeField;
        
        private bool garageField;
        
        private decimal cad_sizeField;
        
        private decimal deed_sizeField;
        
        private double xField;
        
        private double yField;
        
        private string townshipField;
        
        private string registrarField;
        
        private int extensionField;
        
        private decimal nad_idField;
        
        private decimal street_idField;
        
        private string street_numberField;
        
        private string street_nameField;
        
        private string street_typeField;
        
        private int sub_idField;
        
        private string suburbField;
        
        private string idnumberField;
        
        private string fullnameField;
        
        private string firstnameField;
        
        private string middlenameField;
        
        private string surnameField;
        
        private string persontypeField;
        
        private string titledeednumberField;
        
        private string bondnumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
                this.RaisePropertyChanged("user_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string trackingnumer {
            get {
                return this.trackingnumerField;
            }
            set {
                this.trackingnumerField = value;
                this.RaisePropertyChanged("trackingnumer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int MaxRows {
            get {
                return this.maxRowsField;
            }
            set {
                this.maxRowsField = value;
                this.RaisePropertyChanged("MaxRows");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal prop_id {
            get {
                return this.prop_idField;
            }
            set {
                this.prop_idField = value;
                this.RaisePropertyChanged("prop_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal prov_id {
            get {
                return this.prov_idField;
            }
            set {
                this.prov_idField = value;
                this.RaisePropertyChanged("prov_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("province");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int munic_id {
            get {
                return this.munic_idField;
            }
            set {
                this.munic_idField = value;
                this.RaisePropertyChanged("munic_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
                this.RaisePropertyChanged("municipality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string farmname {
            get {
                return this.farmnameField;
            }
            set {
                this.farmnameField = value;
                this.RaisePropertyChanged("farmname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal deed_id {
            get {
                return this.deed_idField;
            }
            set {
                this.deed_idField = value;
                this.RaisePropertyChanged("deed_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string deedtown {
            get {
                return this.deedtownField;
            }
            set {
                this.deedtownField = value;
                this.RaisePropertyChanged("deedtown");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string erf {
            get {
                return this.erfField;
            }
            set {
                this.erfField = value;
                this.RaisePropertyChanged("erf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string portion {
            get {
                return this.portionField;
            }
            set {
                this.portionField = value;
                this.RaisePropertyChanged("portion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal ss_id {
            get {
                return this.ss_idField;
            }
            set {
                this.ss_idField = value;
                this.RaisePropertyChanged("ss_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string sectional_scheme {
            get {
                return this.sectional_schemeField;
            }
            set {
                this.sectional_schemeField = value;
                this.RaisePropertyChanged("sectional_scheme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string sectional_scheme_no {
            get {
                return this.sectional_scheme_noField;
            }
            set {
                this.sectional_scheme_noField = value;
                this.RaisePropertyChanged("sectional_scheme_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int est_id {
            get {
                return this.est_idField;
            }
            set {
                this.est_idField = value;
                this.RaisePropertyChanged("est_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string estate_name {
            get {
                return this.estate_nameField;
            }
            set {
                this.estate_nameField = value;
                this.RaisePropertyChanged("estate_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string erf_key {
            get {
                return this.erf_keyField;
            }
            set {
                this.erf_keyField = value;
                this.RaisePropertyChanged("erf_key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal proptype_id {
            get {
                return this.proptype_idField;
            }
            set {
                this.proptype_idField = value;
                this.RaisePropertyChanged("proptype_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string property_type {
            get {
                return this.property_typeField;
            }
            set {
                this.property_typeField = value;
                this.RaisePropertyChanged("property_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool garage {
            get {
                return this.garageField;
            }
            set {
                this.garageField = value;
                this.RaisePropertyChanged("garage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public decimal cad_size {
            get {
                return this.cad_sizeField;
            }
            set {
                this.cad_sizeField = value;
                this.RaisePropertyChanged("cad_size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public decimal deed_size {
            get {
                return this.deed_sizeField;
            }
            set {
                this.deed_sizeField = value;
                this.RaisePropertyChanged("deed_size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("x");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("y");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string township {
            get {
                return this.townshipField;
            }
            set {
                this.townshipField = value;
                this.RaisePropertyChanged("township");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string registrar {
            get {
                return this.registrarField;
            }
            set {
                this.registrarField = value;
                this.RaisePropertyChanged("registrar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public int extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("extension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public decimal nad_id {
            get {
                return this.nad_idField;
            }
            set {
                this.nad_idField = value;
                this.RaisePropertyChanged("nad_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public decimal street_id {
            get {
                return this.street_idField;
            }
            set {
                this.street_idField = value;
                this.RaisePropertyChanged("street_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string street_number {
            get {
                return this.street_numberField;
            }
            set {
                this.street_numberField = value;
                this.RaisePropertyChanged("street_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string street_name {
            get {
                return this.street_nameField;
            }
            set {
                this.street_nameField = value;
                this.RaisePropertyChanged("street_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string street_type {
            get {
                return this.street_typeField;
            }
            set {
                this.street_typeField = value;
                this.RaisePropertyChanged("street_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public int sub_id {
            get {
                return this.sub_idField;
            }
            set {
                this.sub_idField = value;
                this.RaisePropertyChanged("sub_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string suburb {
            get {
                return this.suburbField;
            }
            set {
                this.suburbField = value;
                this.RaisePropertyChanged("suburb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string idnumber {
            get {
                return this.idnumberField;
            }
            set {
                this.idnumberField = value;
                this.RaisePropertyChanged("idnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
                this.RaisePropertyChanged("fullname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
                this.RaisePropertyChanged("firstname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string middlename {
            get {
                return this.middlenameField;
            }
            set {
                this.middlenameField = value;
                this.RaisePropertyChanged("middlename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string persontype {
            get {
                return this.persontypeField;
            }
            set {
                this.persontypeField = value;
                this.RaisePropertyChanged("persontype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string titledeednumber {
            get {
                return this.titledeednumberField;
            }
            set {
                this.titledeednumberField = value;
                this.RaisePropertyChanged("titledeednumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string bondnumber {
            get {
                return this.bondnumberField;
            }
            set {
                this.bondnumberField = value;
                this.RaisePropertyChanged("bondnumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PropertiesSoapChannel : Lace.Domain.DataProviders.Lightstone.Property.LspServiceReference.PropertiesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PropertiesSoapClient : System.ServiceModel.ClientBase<Lace.Domain.DataProviders.Lightstone.Property.LspServiceReference.PropertiesSoap>, Lace.Domain.DataProviders.Lightstone.Property.LspServiceReference.PropertiesSoap {
        
        public PropertiesSoapClient() {
        }
        
        public PropertiesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PropertiesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PropertiesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PropertiesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ReturnProperties(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    int MaxRowsToReturn, 
                    string TrackingNumber) {
            return base.Channel.ReturnProperties(User_ID, Province, Municipality, DeedTown, Erf, Portion, Sectional_Title, Unit, Suburb, Street, StreetNumber, Owner_Name, ID_CK, Estate_Name, FARM_NAME, MaxRowsToReturn, TrackingNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnPropertiesAsync(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    int MaxRowsToReturn, 
                    string TrackingNumber) {
            return base.Channel.ReturnPropertiesAsync(User_ID, Province, Municipality, DeedTown, Erf, Portion, Sectional_Title, Unit, Suburb, Street, StreetNumber, Owner_Name, ID_CK, Estate_Name, FARM_NAME, MaxRowsToReturn, TrackingNumber);
        }
        
        public System.Data.DataSet ReturnProperties_Prop_ID(string User_ID, long prop_id, string TrackingNumber) {
            return base.Channel.ReturnProperties_Prop_ID(User_ID, prop_id, TrackingNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnProperties_Prop_IDAsync(string User_ID, long prop_id, string TrackingNumber) {
            return base.Channel.ReturnProperties_Prop_IDAsync(User_ID, prop_id, TrackingNumber);
        }
        
        public System.Data.DataSet ReturnProperties_Alt(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string StreetType, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    string Registrar, 
                    int MaxRowsToReturn, 
                    string TrackingNumber) {
            return base.Channel.ReturnProperties_Alt(User_ID, Province, Municipality, DeedTown, Erf, Portion, Sectional_Title, Unit, Suburb, Street, StreetNumber, StreetType, Owner_Name, ID_CK, Estate_Name, FARM_NAME, Registrar, MaxRowsToReturn, TrackingNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnProperties_AltAsync(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string StreetType, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    string Registrar, 
                    int MaxRowsToReturn, 
                    string TrackingNumber) {
            return base.Channel.ReturnProperties_AltAsync(User_ID, Province, Municipality, DeedTown, Erf, Portion, Sectional_Title, Unit, Suburb, Street, StreetNumber, StreetType, Owner_Name, ID_CK, Estate_Name, FARM_NAME, Registrar, MaxRowsToReturn, TrackingNumber);
        }
        
        public System.Data.DataSet ReturnProperties_Alt_Coords(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string Street_Type, 
                    string Registrar, 
                    string FirstName, 
                    string SecondName, 
                    string Surname, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    int MaxRowsToReturn, 
                    string TrackingNumber, 
                    string x, 
                    string y) {
            return base.Channel.ReturnProperties_Alt_Coords(User_ID, Province, Municipality, DeedTown, Erf, Portion, Sectional_Title, Unit, Suburb, Street, StreetNumber, Street_Type, Registrar, FirstName, SecondName, Surname, Owner_Name, ID_CK, Estate_Name, FARM_NAME, MaxRowsToReturn, TrackingNumber, x, y);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnProperties_Alt_CoordsAsync(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string Street_Type, 
                    string Registrar, 
                    string FirstName, 
                    string SecondName, 
                    string Surname, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    int MaxRowsToReturn, 
                    string TrackingNumber, 
                    string x, 
                    string y) {
            return base.Channel.ReturnProperties_Alt_CoordsAsync(User_ID, Province, Municipality, DeedTown, Erf, Portion, Sectional_Title, Unit, Suburb, Street, StreetNumber, Street_Type, Registrar, FirstName, SecondName, Surname, Owner_Name, ID_CK, Estate_Name, FARM_NAME, MaxRowsToReturn, TrackingNumber, x, y);
        }
        
        public System.Data.DataSet ReturnProperties_Crit(Lace.Domain.DataProviders.Lightstone.Property.LspServiceReference.Property_Search_Criteria Criteria) {
            return base.Channel.ReturnProperties_Crit(Criteria);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnProperties_CritAsync(Lace.Domain.DataProviders.Lightstone.Property.LspServiceReference.Property_Search_Criteria Criteria) {
            return base.Channel.ReturnProperties_CritAsync(Criteria);
        }
        
        public System.Data.DataSet ReturnProperties_SplitNames(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string StreetType, 
                    string FirstName, 
                    string SecondName, 
                    string Surname, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    string Registrar, 
                    int MaxRowsToReturn, 
                    string TrackingNumber) {
            return base.Channel.ReturnProperties_SplitNames(User_ID, Province, Municipality, DeedTown, Erf, Portion, Sectional_Title, Unit, Suburb, Street, StreetNumber, StreetType, FirstName, SecondName, Surname, ID_CK, Estate_Name, FARM_NAME, Registrar, MaxRowsToReturn, TrackingNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnProperties_SplitNamesAsync(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string StreetType, 
                    string FirstName, 
                    string SecondName, 
                    string Surname, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    string Registrar, 
                    int MaxRowsToReturn, 
                    string TrackingNumber) {
            return base.Channel.ReturnProperties_SplitNamesAsync(User_ID, Province, Municipality, DeedTown, Erf, Portion, Sectional_Title, Unit, Suburb, Street, StreetNumber, StreetType, FirstName, SecondName, Surname, ID_CK, Estate_Name, FARM_NAME, Registrar, MaxRowsToReturn, TrackingNumber);
        }
        
        public System.Data.DataSet ReturnProperties_ReqStatus(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string Street_Type, 
                    string StreetNumber, 
                    string StreetType, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    string Registrar, 
                    int MaxRowsToReturn, 
                    string TrackingNumber) {
            return base.Channel.ReturnProperties_ReqStatus(User_ID, Province, Municipality, DeedTown, Erf, Portion, Sectional_Title, Unit, Suburb, Street, Street_Type, StreetNumber, StreetType, Owner_Name, ID_CK, Estate_Name, FARM_NAME, Registrar, MaxRowsToReturn, TrackingNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnProperties_ReqStatusAsync(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string Street_Type, 
                    string StreetNumber, 
                    string StreetType, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    string Registrar, 
                    int MaxRowsToReturn, 
                    string TrackingNumber) {
            return base.Channel.ReturnProperties_ReqStatusAsync(User_ID, Province, Municipality, DeedTown, Erf, Portion, Sectional_Title, Unit, Suburb, Street, Street_Type, StreetNumber, StreetType, Owner_Name, ID_CK, Estate_Name, FARM_NAME, Registrar, MaxRowsToReturn, TrackingNumber);
        }
        
        public System.Data.DataSet ConfirmValidation(string User_ID, string TrackingNumber, int Prop_ID) {
            return base.Channel.ConfirmValidation(User_ID, TrackingNumber, Prop_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ConfirmValidationAsync(string User_ID, string TrackingNumber, int Prop_ID) {
            return base.Channel.ConfirmValidationAsync(User_ID, TrackingNumber, Prop_ID);
        }
        
        public System.Data.DataSet ReturnValuation(string User_ID, string TrackingNumber) {
            return base.Channel.ReturnValuation(User_ID, TrackingNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnValuationAsync(string User_ID, string TrackingNumber) {
            return base.Channel.ReturnValuationAsync(User_ID, TrackingNumber);
        }
        
        public System.Data.DataSet ReturnValuation_Banking(string User_ID, string TrackingNumber, int PurchasePrice, int LoanAmount, bool Advance) {
            return base.Channel.ReturnValuation_Banking(User_ID, TrackingNumber, PurchasePrice, LoanAmount, Advance);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnValuation_BankingAsync(string User_ID, string TrackingNumber, int PurchasePrice, int LoanAmount, bool Advance) {
            return base.Channel.ReturnValuation_BankingAsync(User_ID, TrackingNumber, PurchasePrice, LoanAmount, Advance);
        }
        
        public System.Data.DataSet ReturnPropertyReport(string User_ID, string TrackingNumber) {
            return base.Channel.ReturnPropertyReport(User_ID, TrackingNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnPropertyReportAsync(string User_ID, string TrackingNumber) {
            return base.Channel.ReturnPropertyReportAsync(User_ID, TrackingNumber);
        }
        
        public System.Data.DataSet ReturnSuburbs(string Suburb) {
            return base.Channel.ReturnSuburbs(Suburb);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnSuburbsAsync(string Suburb) {
            return base.Channel.ReturnSuburbsAsync(Suburb);
        }
        
        public System.Data.DataSet ReturnSuburb_Report_WithHistory_Sub_ID(string User_ID, int sub_id, string Trackingnumber) {
            return base.Channel.ReturnSuburb_Report_WithHistory_Sub_ID(User_ID, sub_id, Trackingnumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnSuburb_Report_WithHistory_Sub_IDAsync(string User_ID, int sub_id, string Trackingnumber) {
            return base.Channel.ReturnSuburb_Report_WithHistory_Sub_IDAsync(User_ID, sub_id, Trackingnumber);
        }
        
        public System.Data.DataSet ReturnSuburb_Report_WithHistory(string User_ID, string suburb, string deed_id, string Trackingnumber) {
            return base.Channel.ReturnSuburb_Report_WithHistory(User_ID, suburb, deed_id, Trackingnumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnSuburb_Report_WithHistoryAsync(string User_ID, string suburb, string deed_id, string Trackingnumber) {
            return base.Channel.ReturnSuburb_Report_WithHistoryAsync(User_ID, suburb, deed_id, Trackingnumber);
        }
        
        public System.Data.DataSet ReturnSuburb_Report(string User_ID, string suburb, string deed_id) {
            return base.Channel.ReturnSuburb_Report(User_ID, suburb, deed_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnSuburb_ReportAsync(string User_ID, string suburb, string deed_id) {
            return base.Channel.ReturnSuburb_ReportAsync(User_ID, suburb, deed_id);
        }
        
        public System.Data.DataSet ReturnSuburb_Trends(int sub_id) {
            return base.Channel.ReturnSuburb_Trends(sub_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnSuburb_TrendsAsync(int sub_id) {
            return base.Channel.ReturnSuburb_TrendsAsync(sub_id);
        }
        
        public System.Data.DataSet ReturnTransfers(
                    string user_id, 
                    string Sectional_Title, 
                    string Street, 
                    string Suburb, 
                    string RegDateFrom, 
                    string RegDateTo, 
                    string SalesDateFrom, 
                    string SalesDateTo, 
                    string PriceFrom, 
                    string PriceTo, 
                    int PropType_ID, 
                    string Buyer_Name, 
                    string Deedtown, 
                    string Erf, 
                    string Portion, 
                    string farm, 
                    string ErfSizeFrom, 
                    string ErfSizeTo, 
                    string Estate, 
                    string Ext) {
            return base.Channel.ReturnTransfers(user_id, Sectional_Title, Street, Suburb, RegDateFrom, RegDateTo, SalesDateFrom, SalesDateTo, PriceFrom, PriceTo, PropType_ID, Buyer_Name, Deedtown, Erf, Portion, farm, ErfSizeFrom, ErfSizeTo, Estate, Ext);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnTransfersAsync(
                    string user_id, 
                    string Sectional_Title, 
                    string Street, 
                    string Suburb, 
                    string RegDateFrom, 
                    string RegDateTo, 
                    string SalesDateFrom, 
                    string SalesDateTo, 
                    string PriceFrom, 
                    string PriceTo, 
                    int PropType_ID, 
                    string Buyer_Name, 
                    string Deedtown, 
                    string Erf, 
                    string Portion, 
                    string farm, 
                    string ErfSizeFrom, 
                    string ErfSizeTo, 
                    string Estate, 
                    string Ext) {
            return base.Channel.ReturnTransfersAsync(user_id, Sectional_Title, Street, Suburb, RegDateFrom, RegDateTo, SalesDateFrom, SalesDateTo, PriceFrom, PriceTo, PropType_ID, Buyer_Name, Deedtown, Erf, Portion, farm, ErfSizeFrom, ErfSizeTo, Estate, Ext);
        }
        
        public System.Data.DataSet ReturnOwners(string User_ID, string Person_IDNumber, string Person_Name) {
            return base.Channel.ReturnOwners(User_ID, Person_IDNumber, Person_Name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnOwnersAsync(string User_ID, string Person_IDNumber, string Person_Name) {
            return base.Channel.ReturnOwnersAsync(User_ID, Person_IDNumber, Person_Name);
        }
        
        public System.Data.DataSet ReturnOwners_History(string User_ID, string IDNumbers) {
            return base.Channel.ReturnOwners_History(User_ID, IDNumbers);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnOwners_HistoryAsync(string User_ID, string IDNumbers) {
            return base.Channel.ReturnOwners_HistoryAsync(User_ID, IDNumbers);
        }
        
        public System.Data.DataSet ReturnSectionalSchemes(string Sectional_Scheme_name, string Sectional_Scheme_No) {
            return base.Channel.ReturnSectionalSchemes(Sectional_Scheme_name, Sectional_Scheme_No);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnSectionalSchemesAsync(string Sectional_Scheme_name, string Sectional_Scheme_No) {
            return base.Channel.ReturnSectionalSchemesAsync(Sectional_Scheme_name, Sectional_Scheme_No);
        }
        
        public System.Data.DataSet ReturnSectionalSchemeReport(string user_id, int ss_group_id, string trackingnumber) {
            return base.Channel.ReturnSectionalSchemeReport(user_id, ss_group_id, trackingnumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnSectionalSchemeReportAsync(string user_id, int ss_group_id, string trackingnumber) {
            return base.Channel.ReturnSectionalSchemeReportAsync(user_id, ss_group_id, trackingnumber);
        }
        
        public System.Data.DataSet ReturnEstates(string Estate_Name) {
            return base.Channel.ReturnEstates(Estate_Name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnEstatesAsync(string Estate_Name) {
            return base.Channel.ReturnEstatesAsync(Estate_Name);
        }
        
        public System.Data.DataSet ReturnEstateReport(string user_id, int Estate_ID, string trackingnumber) {
            return base.Channel.ReturnEstateReport(user_id, Estate_ID, trackingnumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnEstateReportAsync(string user_id, int Estate_ID, string trackingnumber) {
            return base.Channel.ReturnEstateReportAsync(user_id, Estate_ID, trackingnumber);
        }
        
        public System.Data.DataSet ReturnLegalEntities(string User_ID, string idnumber, string name, string firstname, string secondname, string surname) {
            return base.Channel.ReturnLegalEntities(User_ID, idnumber, name, firstname, secondname, surname);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnLegalEntitiesAsync(string User_ID, string idnumber, string name, string firstname, string secondname, string surname) {
            return base.Channel.ReturnLegalEntitiesAsync(User_ID, idnumber, name, firstname, secondname, surname);
        }
        
        public System.Data.DataSet ReturnLegalEntitiyReport(string User_ID, int le_id) {
            return base.Channel.ReturnLegalEntitiyReport(User_ID, le_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnLegalEntitiyReportAsync(string User_ID, int le_id) {
            return base.Channel.ReturnLegalEntitiyReportAsync(User_ID, le_id);
        }
        
        public System.Data.DataSet returnHedonicFields() {
            return base.Channel.returnHedonicFields();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> returnHedonicFieldsAsync() {
            return base.Channel.returnHedonicFieldsAsync();
        }
        
        public System.Data.DataSet publishHedonicDataTable(string reqprop_id, string xml) {
            return base.Channel.publishHedonicDataTable(reqprop_id, xml);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> publishHedonicDataTableAsync(string reqprop_id, string xml) {
            return base.Channel.publishHedonicDataTableAsync(reqprop_id, xml);
        }
        
        public string publishHedonicData(string reqprop_id, string fieldname, string fieldvalue) {
            return base.Channel.publishHedonicData(reqprop_id, fieldname, fieldvalue);
        }
        
        public System.Threading.Tasks.Task<string> publishHedonicDataAsync(string reqprop_id, string fieldname, string fieldvalue) {
            return base.Channel.publishHedonicDataAsync(reqprop_id, fieldname, fieldvalue);
        }
        
        public System.Data.DataSet returnOwnersInComplexReport(string User_ID, int complexId, string type) {
            return base.Channel.returnOwnersInComplexReport(User_ID, complexId, type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> returnOwnersInComplexReportAsync(string User_ID, int complexId, string type) {
            return base.Channel.returnOwnersInComplexReportAsync(User_ID, complexId, type);
        }
        
        public System.Data.DataSet returnSGDiagramsReport(string User_ID, int office, int urbanRural, string town, int erf, int portion, string farm) {
            return base.Channel.returnSGDiagramsReport(User_ID, office, urbanRural, town, erf, portion, farm);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> returnSGDiagramsReportAsync(string User_ID, int office, int urbanRural, string town, int erf, int portion, string farm) {
            return base.Channel.returnSGDiagramsReportAsync(User_ID, office, urbanRural, town, erf, portion, farm);
        }
        
        public System.Data.DataSet returnQuickValuation(string User_ID, string ReqProp_ID) {
            return base.Channel.returnQuickValuation(User_ID, ReqProp_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> returnQuickValuationAsync(string User_ID, string ReqProp_ID) {
            return base.Channel.returnQuickValuationAsync(User_ID, ReqProp_ID);
        }
        
        public System.Data.DataSet returnTowns(string townname) {
            return base.Channel.returnTowns(townname);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> returnTownsAsync(string townname) {
            return base.Channel.returnTownsAsync(townname);
        }
        
        public System.Data.DataSet returnTownReport(string user_id, int town_id, string trackingnumber) {
            return base.Channel.returnTownReport(user_id, town_id, trackingnumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> returnTownReportAsync(string user_id, int town_id, string trackingnumber) {
            return base.Channel.returnTownReportAsync(user_id, town_id, trackingnumber);
        }
        
        public System.Data.DataSet returnTownReportFromID(string tr_guid) {
            return base.Channel.returnTownReportFromID(tr_guid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> returnTownReportFromIDAsync(string tr_guid) {
            return base.Channel.returnTownReportFromIDAsync(tr_guid);
        }
        
        public System.Data.DataSet returnPropertyInsuranceReport(int prop_id, string user_id, string trackingnumber) {
            return base.Channel.returnPropertyInsuranceReport(prop_id, user_id, trackingnumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> returnPropertyInsuranceReportAsync(int prop_id, string user_id, string trackingnumber) {
            return base.Channel.returnPropertyInsuranceReportAsync(prop_id, user_id, trackingnumber);
        }
        
        public System.Data.DataSet returnStreets(int sub_id, string street_name) {
            return base.Channel.returnStreets(sub_id, street_name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> returnStreetsAsync(int sub_id, string street_name) {
            return base.Channel.returnStreetsAsync(sub_id, street_name);
        }
        
        public System.Data.DataSet ReturnProperties_address(string user_id, string address) {
            return base.Channel.ReturnProperties_address(user_id, address);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnProperties_addressAsync(string user_id, string address) {
            return base.Channel.ReturnProperties_addressAsync(user_id, address);
        }
    }
}
