//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lace.Domain.DataProviders.Lightstone.Consumer.Specifications.LightsoneSpecificationsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.lightstoneconsumer.co.za/SQSServices", ConfigurationName="LightsoneSpecificationsServiceReference.SQSServicesSoap")]
    public interface SQSServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lightstoneconsumer.co.za/SQSServices/getRepairHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getRepairHistory(System.Guid AccessKey, string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lightstoneconsumer.co.za/SQSServices/getRepairHistory", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getRepairHistoryAsync(System.Guid AccessKey, string VIN);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SQSServicesSoapChannel : Lace.Domain.DataProviders.Lightstone.Consumer.Specifications.LightsoneSpecificationsServiceReference.SQSServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SQSServicesSoapClient : System.ServiceModel.ClientBase<Lace.Domain.DataProviders.Lightstone.Consumer.Specifications.LightsoneSpecificationsServiceReference.SQSServicesSoap>, Lace.Domain.DataProviders.Lightstone.Consumer.Specifications.LightsoneSpecificationsServiceReference.SQSServicesSoap {
        
        public SQSServicesSoapClient() {
        }
        
        public SQSServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SQSServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SQSServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SQSServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getRepairHistory(System.Guid AccessKey, string VIN) {
            return base.Channel.getRepairHistory(AccessKey, VIN);
        }
        
        public System.Threading.Tasks.Task<string> getRepairHistoryAsync(System.Guid AccessKey, string VIN) {
            return base.Channel.getRepairHistoryAsync(AccessKey, VIN);
        }
    }
}
