using System.Collections.Generic;

namespace Lace.Test.Helper.Mothers.Sources.Lightstone
{
    public class CarData
    {
        //public static IEnumerable<Car> ForCarOnly()
        //{
        //    return new List<Car>()
        //    {
        //        new Car(107483, 791, "TOYOTA Auris 1.6 RT 5-dr", "Auris 1.6 RT 5-dr", "Hatch (5-dr)", "Petrol", "PAS",
        //            "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107483_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107483_1_S.jpg", "Quickpic"),
        //        new Car(107484, 791, "TOYOTA Auris 1.6 RS 5-dr", "Auris 1.6 RS 5-dr", "Hatch (5-dr)", "Petrol", "PAS",
        //            "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107484_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107484_1_S.jpg", "Quickpic"),
        //        new Car(107485, 791, "TOYOTA Auris 1.6 RS MMT 5-dr", "Auris 1.6 RS MMT 5-dr", "Hatch (5-dr)", "Petrol",
        //            "PAS", "Elec", false, "http://www.rgt.co.za/photos/TOYOTA/107485_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107485_1_S.jpg", "Quickpic"),
        //        new Car(107486, 791, "TOYOTA Auris 1.8 RS 5-dr", "Auris 1.8 RS 5-dr", "Hatch (5-dr)", "Petrol", "PAS",
        //            "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107486_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107486_1_S.jpg", "Quickpic"),
        //        new Car(107487, 791, "TOYOTA Auris 1.8 RX 5-dr", "Auris 1.8 RX 5-dr", "Hatch (5-dr)", "Petrol", "PAS",
        //            "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107487_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107487_1_S.jpg", "Quickpic"),
        //        new Car(107488, 791, "TOYOTA Auris 2.0 RS D-4D 5-dr Dsl", "Auris 2.0 RS D-4D 5-dr Dsl", "Hatch (5-dr)",
        //            "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107488_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107488_1_S.jpg", "Quickpic"),
        //        new Car(107489, 791, "TOYOTA Auris 2.0 RX D-4D 5-dr Dsl", "Auris 2.0 RX D-4D 5-dr Dsl", "Hatch (5-dr)",
        //            "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107489_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107489_1_S.jpg", "Quickpic"),
        //        new Car(107490, 587, "MITSUBISHI Triton 2.4 MPi D-Cab PU", "Triton 2.4 MPi D-Cab PU",
        //            "Double Cab Pick-Up", "Petrol", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/MITSUBISHI/107490_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MITSUBISHI/107490_1_S.jpg", "Quickpic"),
        //        new Car(107491, 587, "MITSUBISHI Triton 3.2 Di-DC 4x4 D-Cab Dsl PU", "Triton 3.2 Di-DC 4x4 D-Cab Dsl PU",
        //            "Double Cab Pick-Up", "Diesel", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/MITSUBISHI/107491_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MITSUBISHI/107491_1_S.jpg", "Quickpic"),
        //        new Car(107492, 587, "MITSUBISHI Triton 3.2 Di-DC 4x4 D-Cab Dsl AT PU",
        //            "Triton 3.2 Di-DC 4x4 D-Cab Dsl AT PU", "Double Cab Pick-Up", "Diesel", "LCV", "Auto", false,
        //            "http://www.rgt.co.za/photos/MITSUBISHI/107492_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MITSUBISHI/107492_1_S.jpg", "Quickpic"),
        //        new Car(107493, 587, "MITSUBISHI Triton 3.5 MPi 4x4 D-Cab PU", "Triton 3.5 MPi 4x4 D-Cab PU",
        //            "Double Cab Pick-Up", "Petrol", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/MITSUBISHI/107493_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MITSUBISHI/107493_1_S.jpg", "Quickpic"),
        //        new Car(107495, 848, "VOLVO FM9 340 S/R DC I-Shift 6x4 F-C", "FM9 340 S/R DC I-Shift 6x4 F-C",
        //            "Freight Carrier", "Diesel", "XHV", "Elec", false, "/images/Lightstone-auto-car.png",
        //            "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107496, 389, "IVECO Trakker AD260T38 6x4 F-C", "Trakker AD260T38 6x4 F-C", "Freight Carrier",
        //            "Diesel", "XHV", "Man", false, "/images/Lightstone-auto-car.png",
        //            "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107497, 897, "VOLKSWAGEN T5 California 2.5 TDi 128kW Dsl MPV 4Motion",
        //            "T5 California 2.5 TDi 128kW Dsl MPV 4Motion", "MPV", "Diesel", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107497_1_P.jpg",
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107497_1_S.jpg", "Manufacturer"),
        //        new Car(107498, 897, "VOLKSWAGEN T5 Beach 1.9 TDi 77kW Dsl MPV", "T5 Beach 1.9 TDi 77kW Dsl MPV", "MPV",
        //            "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/VOLKSWAGEN/107498_1_P.jpg",
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107498_1_S.jpg", "Manufacturer"),
        //        new Car(107499, 897, "VOLKSWAGEN T5 Beach 2.5 TDi 128kW Dsl MPV", "T5 Beach 2.5 TDi 128kW Dsl MPV",
        //            "MPV", "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/VOLKSWAGEN/107499_1_P.jpg",
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107499_1_S.jpg", "Manufacturer"),
        //        new Car(107500, 897, "VOLKSWAGEN T5 Beach 2.5 TDi 128kW Dsl MPV 4Motion",
        //            "T5 Beach 2.5 TDi 128kW Dsl MPV 4Motion", "MPV", "Diesel", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107500_1_P.jpg",
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107500_1_S.jpg", "Manufacturer"),
        //        new Car(107501, 44, "AUDI A6 4.2 FSi Quattro Security Tiptronic",
        //            "A6 4.2 FSi Quattro Security Tiptronic", "Sedan", "Petrol", "PAS", "Elec", false,
        //            "http://www.rgt.co.za/photos/AUDI/107501_1_P.jpg", "http://www.rgt.co.za/photos/AUDI/107501_1_S.jpg",
        //            "Motorpic"),
        //        new Car(107502, 44, "AUDI A6 2.8 FSi Multitronic 7-sp", "A6 2.8 FSi Multitronic 7-sp", "Sedan", "Petrol",
        //            "PAS", "Elec", false, "http://www.rgt.co.za/photos/AUDI/107502_1_P.jpg",
        //            "http://www.rgt.co.za/photos/AUDI/107502_1_S.jpg", "Motorpic"),
        //        new Car(107503, 887, "VOLKSWAGEN Polo 1.4 Trendline 3-dr Tiptronic Exp",
        //            "Polo 1.4 Trendline 3-dr Tiptronic Exp", "Hatch (3-dr)", "Petrol", "PAS", "Elec", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107504, 875, "VOLKSWAGEN Golf 5 2.0 TDi GT Sport 3-dr Dsl Exp",
        //            "Golf 5 2.0 TDi GT Sport 3-dr Dsl Exp", "Hatch (3-dr)", "Diesel", "PAS", "Man", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107505, 887, "VOLKSWAGEN Polo 1.4 Comfortline 3-dr Tiptronic Exp",
        //            "Polo 1.4 Comfortline 3-dr Tiptronic Exp", "Hatch (3-dr)", "Petrol", "PAS", "Elec", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107506, 506, "MAZDA Mazda3 Sport 2.3 MPS DiSi Turbo 5-dr",
        //            "Mazda3 Sport 2.3 MPS DiSi Turbo 5-dr", "Hatch (5-dr)", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/MAZDA/107506_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MAZDA/107506_1_S.jpg", "Quickpic"),
        //        new Car(107507, 888, "VOLKSWAGEN Polo Classic 1.6 Comfortline Tiptronic",
        //            "Polo Classic 1.6 Comfortline Tiptronic", "Sedan", "Petrol", "PAS", "Elec", false,
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107507_1_P.jpg",
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107507_1_S.jpg", "Motorpic"),
        //        new Car(107508, 242, "FIAT Panda 1.4 100HP 5-dr", "Panda 1.4 100HP 5-dr", "Hatch (5-dr)", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/FIAT/107508_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FIAT/107508_1_S.jpg", "Quickpic"),
        //        new Car(107510, 396, "JAGUAR X-Type 2.0 SE AT MY08", "X-Type 2.0 SE AT MY08", "Sedan", "Petrol", "PAS",
        //            "Elec", false, "http://www.rgt.co.za/photos/JAGUAR/107510_1_P.jpg",
        //            "http://www.rgt.co.za/photos/JAGUAR/107510_1_S.jpg", "Quickpic"),
        //        new Car(107511, 396, "JAGUAR X-Type 2.2D SE Dsl MY08", "X-Type 2.2D SE Dsl MY08", "Sedan", "Diesel",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/JAGUAR/107511_1_P.jpg",
        //            "http://www.rgt.co.za/photos/JAGUAR/107511_1_S.jpg", "Quickpic"),
        //        new Car(107512, 396, "JAGUAR X-Type 3.0 SE AWD AT MY08", "X-Type 3.0 SE AWD AT MY08", "Sedan", "Petrol",
        //            "PAS", "Elec", false, "http://www.rgt.co.za/photos/JAGUAR/107512_1_P.jpg",
        //            "http://www.rgt.co.za/photos/JAGUAR/107512_1_S.jpg", "Quickpic"),
        //        new Car(107513, 603, "NISSAN Livina 1.6 Visia 5-dr", "Livina 1.6 Visia 5-dr", "Hatch (5-dr)", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/NISSAN/107513_1_P.jpg",
        //            "http://www.rgt.co.za/photos/NISSAN/107513_1_S.jpg", "Quickpic"),
        //        new Car(107514, 603, "NISSAN Livina 1.6 Acenta 5-dr", "Livina 1.6 Acenta 5-dr", "Hatch (5-dr)", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/NISSAN/107514_1_P.jpg",
        //            "http://www.rgt.co.za/photos/NISSAN/107514_1_S.jpg", "Quickpic"),
        //        new Car(107515, 603, "NISSAN Livina 1.6 Acenta+ 5-dr", "Livina 1.6 Acenta+ 5-dr", "Hatch (5-dr)",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/NISSAN/107515_1_P.jpg",
        //            "http://www.rgt.co.za/photos/NISSAN/107515_1_S.jpg", "Quickpic"),
        //        new Car(107516, 597, "NISSAN Grand Livina 1.6 Acenta MPV", "Grand Livina 1.6 Acenta MPV", "MPV",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/NISSAN/107516_1_P.jpg",
        //            "http://www.rgt.co.za/photos/NISSAN/107516_1_S.jpg", "Quickpic"),
        //        new Car(107517, 597, "NISSAN Grand Livina 1.6 Acenta+ MPV", "Grand Livina 1.6 Acenta+ MPV", "MPV",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/NISSAN/107517_1_P.jpg",
        //            "http://www.rgt.co.za/photos/NISSAN/107517_1_S.jpg", "Quickpic"),
        //        new Car(107518, 897, "VOLKSWAGEN T5 California 2.5 TDi 128kW Dsl MPV",
        //            "T5 California 2.5 TDi 128kW Dsl MPV", "MPV", "Diesel", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107518_1_P.jpg",
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107518_1_S.jpg", "Manufacturer"),
        //        new Car(107519, 242, "FIAT Panda 1.1 Active 5-dr", "Panda 1.1 Active 5-dr", "Hatch (5-dr)", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/FIAT/107519_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FIAT/107519_1_S.jpg", "Quickpic"),
        //        new Car(107520, 252, "FIAT Uno 1.2 3-dr", "Uno 1.2 3-dr", "Hatch (3-dr)", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/FIAT/107520_1_P.jpg", "http://www.rgt.co.za/photos/FIAT/107520_1_S.jpg",
        //            "Quickpic"),
        //        new Car(107521, 252, "FIAT Uno 1.2 5-dr", "Uno 1.2 5-dr", "Hatch (5-dr)", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/FIAT/107521_1_P.jpg", "http://www.rgt.co.za/photos/FIAT/107521_1_S.jpg",
        //            "Quickpic"),
        //        new Car(107522, 252, "FIAT Uno 1.2 Way 5-dr", "Uno 1.2 Way 5-dr", "Hatch (5-dr)", "Petrol", "PAS", "Man",
        //            false, "http://www.rgt.co.za/photos/FIAT/107522_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FIAT/107522_1_S.jpg", "Quickpic"),
        //        new Car(107523, 252, "FIAT Uno 1.2 P-Van", "Uno 1.2 P-Van", "Panel Van", "Petrol", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/FIAT/107523_1_P.jpg", "http://www.rgt.co.za/photos/FIAT/107523_1_S.jpg",
        //            "Quickpic"),
        //        new Car(107524, 706, "RENAULT Megane II Hatch RenaultSport 2.0T R26 3-dr",
        //            "Megane II Hatch RenaultSport 2.0T R26 3-dr", "Hatch (3-dr)", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/RENAULT/107524_1_P.jpg",
        //            "http://www.rgt.co.za/photos/RENAULT/107524_1_S.jpg", "Quickpic"),
        //        new Car(107526, 168, "DFM Mini Truck 1.3 PU", "Mini Truck 1.3 PU", "Single Cab Pick-Up", "Petrol", "LCV",
        //            "Man", false, "http://www.rgt.co.za/photos/DFM/107526_1_P.jpg",
        //            "http://www.rgt.co.za/photos/DFM/107526_1_S.jpg", "Manufacturer"),
        //        new Car(107527, 167, "DFM Mini Panel Van 1.3 P-Van", "Mini Panel Van 1.3 P-Van", "Panel Van", "Petrol",
        //            "LCV", "Man", false, "http://www.rgt.co.za/photos/DFM/107527_1_P.jpg",
        //            "http://www.rgt.co.za/photos/DFM/107527_1_S.jpg", "Manufacturer"),
        //        new Car(107528, 166, "DFM Cargo Van 1.3 P-Van", "Cargo Van 1.3 P-Van", "Panel Van", "Petrol", "LCV",
        //            "Man", false, "http://www.rgt.co.za/photos/DFM/107528_1_P.jpg",
        //            "http://www.rgt.co.za/photos/DFM/107528_1_S.jpg", "Manufacturer"),
        //        new Car(107529, 46, "AUDI A6 Avant 3.0 TDi Quattro Tiptronic Dsl MY08",
        //            "A6 Avant 3.0 TDi Quattro Tiptronic Dsl MY08", "Estate", "Diesel", "PAS", "Elec", false,
        //            "http://www.rgt.co.za/photos/AUDI/107529_1_P.jpg", "http://www.rgt.co.za/photos/AUDI/107529_1_S.jpg",
        //            "Motorpic"),
        //        new Car(107530, 287, "FUDI Lion 2.2 Basic PU", "Lion 2.2 Basic PU", "Single Cab Pick-Up", "Petrol",
        //            "LCV", "Man", false, "http://www.rgt.co.za/photos/FUDI/107530_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FUDI/107530_1_S.jpg", "Manufacturer"),
        //        new Car(107531, 287, "FUDI Lion 2.2 Deluxe PU", "Lion 2.2 Deluxe PU", "Single Cab Pick-Up", "Petrol",
        //            "LCV", "Man", false, "http://www.rgt.co.za/photos/FUDI/107531_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FUDI/107531_1_S.jpg", "Manufacturer"),
        //        new Car(107532, 287, "FUDI Lion 2.8 Deluxe Dsl PU", "Lion 2.8 Deluxe Dsl PU", "Single Cab Pick-Up",
        //            "Diesel", "LCV", "Man", false, "http://www.rgt.co.za/photos/FUDI/107532_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FUDI/107532_1_S.jpg", "Manufacturer"),
        //        new Car(107533, 287, "FUDI Lion 2.2 D-Cab Deluxe PU", "Lion 2.2 D-Cab Deluxe PU", "Double Cab Pick-Up",
        //            "Petrol", "LCV", "Man", false, "http://www.rgt.co.za/photos/FUDI/107533_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FUDI/107533_1_S.jpg", "Manufacturer"),
        //        new Car(107534, 287, "FUDI Lion 2.8 D-Cab Deluxe Dsl PU", "Lion 2.8 D-Cab Deluxe Dsl PU",
        //            "Double Cab Pick-Up", "Diesel", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/FUDI/107534_1_P.jpg", "http://www.rgt.co.za/photos/FUDI/107534_1_S.jpg",
        //            "Manufacturer"),
        //        new Car(107536, 235, "FIAT Ducato 2.3 L-MH1 P-Van Dsl", "Ducato 2.3 L-MH1 P-Van Dsl", "Panel Van",
        //            "Diesel", "MCV", "Man", false, "http://www.rgt.co.za/photos/FIAT/107536_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FIAT/107536_1_S.jpg", "Quickpic"),
        //        new Car(107537, 235, "FIAT Ducato 2.3 L-MH2 High Roof P-Van Dsl", "Ducato 2.3 L-MH2 High Roof P-Van Dsl",
        //            "Panel Van", "Diesel", "MCV", "Man", false, "http://www.rgt.co.za/photos/FIAT/107537_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FIAT/107537_1_S.jpg", "Quickpic"),
        //        new Car(107538, 235, "FIAT Ducato 2.3 L-LH2 High Roof P-Van Dsl", "Ducato 2.3 L-LH2 High Roof P-Van Dsl",
        //            "Panel Van", "Diesel", "MCV", "Man", false, "http://www.rgt.co.za/photos/FIAT/107538_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FIAT/107538_1_S.jpg", "Quickpic"),
        //        new Car(107540, 528, "MEIYA Pickup 2.2 PU", "Pickup 2.2 PU", "Single Cab Pick-Up", "Petrol", "LCV",
        //            "Man", false, "http://www.rgt.co.za/photos/MEIYA/107540_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MEIYA/107540_1_S.jpg", "Manufacturer"),
        //        new Car(107541, 528, "MEIYA Pickup 2.2 Deluxe PU", "Pickup 2.2 Deluxe PU", "Single Cab Pick-Up",
        //            "Petrol", "LCV", "Man", false, "http://www.rgt.co.za/photos/MEIYA/107541_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MEIYA/107541_1_S.jpg", "Manufacturer"),
        //        new Car(107543, 314, "HONDA Accord 2.0 Executive", "Accord 2.0 Executive", "Sedan", "Petrol", "PAS",
        //            "Man", false, "http://www.rgt.co.za/photos/HONDA/107543_1_P.jpg",
        //            "http://www.rgt.co.za/photos/HONDA/107543_1_S.jpg", "Quickpic"),
        //        new Car(107544, 314, "HONDA Accord 2.0 Executive AT", "Accord 2.0 Executive AT", "Sedan", "Petrol",
        //            "PAS", "Elec", false, "http://www.rgt.co.za/photos/HONDA/107544_1_P.jpg",
        //            "http://www.rgt.co.za/photos/HONDA/107544_1_S.jpg", "Quickpic"),
        //        new Car(107545, 528, "MEIYA Pickup 2.8 TD Deluxe Dsl PU", "Pickup 2.8 TD Deluxe Dsl PU",
        //            "Single Cab Pick-Up", "Diesel", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/MEIYA/107545_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MEIYA/107545_1_S.jpg", "Manufacturer"),
        //        new Car(107546, 528, "MEIYA Pickup 2.2 D-Cab PU", "Pickup 2.2 D-Cab PU", "Double Cab Pick-Up", "Petrol",
        //            "LCV", "Man", false, "http://www.rgt.co.za/photos/MEIYA/107546_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MEIYA/107546_1_S.jpg", "Manufacturer"),
        //        new Car(107547, 528, "MEIYA Pickup 2.2 D-Cab Deluxe PU", "Pickup 2.2 D-Cab Deluxe PU",
        //            "Double Cab Pick-Up", "Petrol", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/MEIYA/107547_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MEIYA/107547_1_S.jpg", "Public Domain"),
        //        new Car(107548, 528, "MEIYA Pickup 2.8 TD D-Cab Deluxe Dsl PU", "Pickup 2.8 TD D-Cab Deluxe Dsl PU",
        //            "Double Cab Pick-Up", "Diesel", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/MEIYA/107548_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MEIYA/107548_1_S.jpg", "Public Domain"),
        //        new Car(107549, 529, "MEIYA Wagon 2.2", "Wagon 2.2", "SUV", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/MEIYA/107549_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MEIYA/107549_1_S.jpg", "Manufacturer"),
        //        new Car(107550, 529, "MEIYA Wagon 2.2 Deluxe", "Wagon 2.2 Deluxe", "SUV", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/MEIYA/107550_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MEIYA/107550_1_S.jpg", "Manufacturer"),
        //        new Car(107551, 631, "OPEL Corsa Lite 1.4i 3-dr MY02", "Corsa Lite 1.4i 3-dr MY02", "Hatch (3-dr)",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/OPEL/107551_1_P.jpg",
        //            "http://www.rgt.co.za/photos/OPEL/107551_1_S.jpg", "Motorpic"),
        //        new Car(107552, 867, "VOLKSWAGEN Constellation 13.180 MWB 4x2 Day F-C",
        //            "Constellation 13.180 MWB 4x2 Day F-C", "Freight Carrier", "Diesel", "HCV", "Man", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107553, 867, "VOLKSWAGEN Constellation 13.180 LWB 4x2 Day F-C",
        //            "Constellation 13.180 LWB 4x2 Day F-C", "Freight Carrier", "Diesel", "HCV", "Man", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107554, 867, "VOLKSWAGEN Constellation 15.180 MWB 4x2 Day F-C",
        //            "Constellation 15.180 MWB 4x2 Day F-C", "Freight Carrier", "Diesel", "HCV", "Man", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107555, 867, "VOLKSWAGEN Constellation 15.180 LWB 4x2 Day F-C",
        //            "Constellation 15.180 LWB 4x2 Day F-C", "Freight Carrier", "Diesel", "HCV", "Man", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107556, 867, "VOLKSWAGEN Constellation 17.250 LWB 4x2 Day F-C MY07",
        //            "Constellation 17.250 LWB 4x2 Day F-C MY07", "Freight Carrier", "Diesel", "XHV", "Man", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107557, 867, "VOLKSWAGEN Constellation 17.250 LWB 4x2 Sleep F-C",
        //            "Constellation 17.250 LWB 4x2 Sleep F-C", "Freight Carrier", "Diesel", "XHV", "Man", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107558, 867, "VOLKSWAGEN Constellation 24.250 LWB 6x2 Day F-C MY07",
        //            "Constellation 24.250 LWB 6x2 Day F-C MY07", "Freight Carrier", "Diesel", "XHV", "Man", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107559, 867, "VOLKSWAGEN Constellation 24.250 LWB 6x2 Sleep F-C",
        //            "Constellation 24.250 LWB 6x2 Sleep F-C", "Freight Carrier", "Diesel", "XHV", "Man", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107560, 867, "VOLKSWAGEN Constellation 19.320 SWB 4x2 Day T-T",
        //            "Constellation 19.320 SWB 4x2 Day T-T", "Truck-Tractor", "Diesel", "XHV", "Man", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107561, 867, "VOLKSWAGEN Constellation 19.320 SWB 4x2 Sleep T-T",
        //            "Constellation 19.320 SWB 4x2 Sleep T-T", "Truck-Tractor", "Diesel", "XHV", "Man", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107562, 542, "MERCEDES C200 K Classic MY07", "C200 K Classic MY07", "Sedan", "Petrol", "PAS",
        //            "Man", false, "http://www.rgt.co.za/photos/MERCEDES/107562_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MERCEDES/107562_1_S.jpg", "Quickpic"),
        //        new Car(107563, 542, "MERCEDES C220 CDi Classic Dsl MY07", "C220 CDi Classic Dsl MY07", "Sedan",
        //            "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/MERCEDES/107563_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MERCEDES/107563_1_S.jpg", "Quickpic"),
        //        new Car(107564, 542, "MERCEDES C280 Elegance 7-sp AT MY07", "C280 Elegance 7-sp AT MY07", "Sedan",
        //            "Petrol", "PAS", "Elec", false, "http://www.rgt.co.za/photos/MERCEDES/107564_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MERCEDES/107564_1_S.jpg", "Quickpic"),
        //        new Car(107565, 542, "MERCEDES C320 CDi Elegance 7-sp Dsl AT MY07", "C320 CDi Elegance 7-sp Dsl AT MY07",
        //            "Sedan", "Diesel", "PAS", "Elec", false, "http://www.rgt.co.za/photos/MERCEDES/107565_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MERCEDES/107565_1_S.jpg", "Quickpic"),
        //        new Car(107566, 542, "MERCEDES C350 Elegance 7-sp AT MY07", "C350 Elegance 7-sp AT MY07", "Sedan",
        //            "Petrol", "PAS", "Elec", false, "http://www.rgt.co.za/photos/MERCEDES/107566_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MERCEDES/107566_1_S.jpg", "Quickpic"),
        //        new Car(107567, 542, "MERCEDES C200 K Classic MY07 AT", "C200 K Classic MY07 AT", "Sedan", "Petrol",
        //            "PAS", "Auto", false, "http://www.rgt.co.za/photos/MERCEDES/107567_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MERCEDES/107567_1_S.jpg", "Quickpic"),
        //        new Car(107568, 542, "MERCEDES C220 CDi Classic Dsl MY07 AT", "C220 CDi Classic Dsl MY07 AT", "Sedan",
        //            "Diesel", "PAS", "Auto", false, "http://www.rgt.co.za/photos/MERCEDES/107568_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MERCEDES/107568_1_S.jpg", "Quickpic"),
        //        new Car(107569, 94, "CHEVROLET Captiva 2.4 LT 5-dr", "Captiva 2.4 LT 5-dr", "SUV", "Petrol", "PAS",
        //            "Man", false, "http://www.rgt.co.za/photos/CHEVROLET/107569_1_P.jpg",
        //            "http://www.rgt.co.za/photos/CHEVROLET/107569_1_S.jpg", "Motorpic"),
        //        new Car(107570, 231, "FIAT Bravo 1.4 T-Jet Active 5-dr", "Bravo 1.4 T-Jet Active 5-dr", "Hatch (5-dr)",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/FIAT/107570_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FIAT/107570_1_S.jpg", "Quickpic"),
        //        new Car(107571, 800, "TOYOTA Corolla 1.4 Professional", "Corolla 1.4 Professional", "Sedan", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107571_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107571_1_S.jpg", "Quickpic"),
        //        new Car(107572, 800, "TOYOTA Corolla 1.4 Advanced", "Corolla 1.4 Advanced", "Sedan", "Petrol", "PAS",
        //            "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107572_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107572_1_S.jpg", "Quickpic"),
        //        new Car(107573, 800, "TOYOTA Corolla 1.6 Professional", "Corolla 1.6 Professional", "Sedan", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107573_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107573_1_S.jpg", "Quickpic"),
        //        new Car(107574, 800, "TOYOTA Corolla 1.6 Advanced", "Corolla 1.6 Advanced", "Sedan", "Petrol", "PAS",
        //            "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107574_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107574_1_S.jpg", "Quickpic"),
        //        new Car(107575, 800, "TOYOTA Corolla 1.6 Advanced MMT", "Corolla 1.6 Advanced MMT", "Sedan", "Petrol",
        //            "PAS", "Elec", false, "http://www.rgt.co.za/photos/TOYOTA/107575_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107575_1_S.jpg", "Quickpic"),
        //        new Car(107576, 800, "TOYOTA Corolla 1.8 Advanced", "Corolla 1.8 Advanced", "Sedan", "Petrol", "PAS",
        //            "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107576_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107576_1_S.jpg", "Quickpic"),
        //        new Car(107577, 800, "TOYOTA Corolla 1.8 Exclusive", "Corolla 1.8 Exclusive", "Sedan", "Petrol", "PAS",
        //            "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107577_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107577_1_S.jpg", "Quickpic"),
        //        new Car(107578, 800, "TOYOTA Corolla 1.8 Exclusive AT", "Corolla 1.8 Exclusive AT", "Sedan", "Petrol",
        //            "PAS", "Auto", false, "http://www.rgt.co.za/photos/TOYOTA/107578_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107578_1_S.jpg", "Quickpic"),
        //        new Car(107579, 800, "TOYOTA Corolla 2.0 D-4D Advanced Dsl", "Corolla 2.0 D-4D Advanced Dsl", "Sedan",
        //            "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107579_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107579_1_S.jpg", "Quickpic"),
        //        new Car(107580, 800, "TOYOTA Corolla 2.0 D-4D Exclusive Dsl", "Corolla 2.0 D-4D Exclusive Dsl", "Sedan",
        //            "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107580_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107580_1_S.jpg", "Quickpic"),
        //        new Car(107581, 829, "TOYOTA Corolla Verso 160 MPV MY07", "Corolla Verso 160 MPV MY07", "MPV", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107581_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107581_1_S.jpg", "Manufacturer"),
        //        new Car(107582, 829, "TOYOTA Corolla Verso 160 SX MPV MY07", "Corolla Verso 160 SX MPV MY07", "MPV",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107582_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107582_1_S.jpg", "Manufacturer"),
        //        new Car(107583, 829, "TOYOTA Corolla Verso 180 TX MPV MY07", "Corolla Verso 180 TX MPV MY07", "MPV",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/TOYOTA/107583_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107583_1_S.jpg", "Manufacturer"),
        //        new Car(107584, 687, "RENAULT Clio III 1.6 Expression 5-dr MY07", "Clio III 1.6 Expression 5-dr MY07",
        //            "Hatch (5-dr)", "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/RENAULT/107584_1_P.jpg",
        //            "http://www.rgt.co.za/photos/RENAULT/107584_1_S.jpg", "Quickpic"),
        //        new Car(107587, 231, "FIAT Bravo 1.4 T-Jet Dynamic 5-dr", "Bravo 1.4 T-Jet Dynamic 5-dr", "Hatch (5-dr)",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/FIAT/107587_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FIAT/107587_1_S.jpg", "Quickpic"),
        //        new Car(107588, 231, "FIAT Bravo 1.4 T-Jet Sport 5-dr", "Bravo 1.4 T-Jet Sport 5-dr", "Hatch (5-dr)",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/FIAT/107588_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FIAT/107588_1_S.jpg", "Quickpic"),
        //        new Car(107589, 231, "FIAT Bravo 1.9 Multijet Dynamic Dsl 5-dr", "Bravo 1.9 Multijet Dynamic Dsl 5-dr",
        //            "Hatch (5-dr)", "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/FIAT/107589_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FIAT/107589_1_S.jpg", "Quickpic"),
        //        new Car(107590, 859, "VOLVO XC70 3.2 AWD Geartronic Estate", "XC70 3.2 AWD Geartronic Estate",
        //            "Crossover", "Petrol", "PAS", "Elec", false, "http://www.rgt.co.za/photos/VOLVO/107590_1_P.jpg",
        //            "http://www.rgt.co.za/photos/VOLVO/107590_1_S.jpg", "Quickpic"),
        //        new Car(107591, 859, "VOLVO XC70 D5 2.4 AWD Geartronic Dsl Estate",
        //            "XC70 D5 2.4 AWD Geartronic Dsl Estate", "Crossover", "Diesel", "PAS", "Elec", false,
        //            "http://www.rgt.co.za/photos/VOLVO/107591_1_P.jpg",
        //            "http://www.rgt.co.za/photos/VOLVO/107591_1_S.jpg", "Quickpic"),
        //        new Car(107593, 867, "VOLKSWAGEN Constellation 17.250 MWB 4x2 Day F-C MY07",
        //            "Constellation 17.250 MWB 4x2 Day F-C MY07", "Freight Carrier", "Diesel", "XHV", "Man", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107594, 429, "LAND ROVER Defender 90 Puma SW 2.4D 4x4 Dsl", "Defender 90 Puma SW 2.4D 4x4 Dsl",
        //            "SUV", "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/LAND ROVER/107594_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LAND ROVER/107594_1_S.jpg", "Quickpic"),
        //        new Car(107595, 429, "LAND ROVER Defender 110 Puma SW 2.4D 4x4 Dsl", "Defender 110 Puma SW 2.4D 4x4 Dsl",
        //            "SUV", "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/LAND ROVER/107595_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LAND ROVER/107595_1_S.jpg", "Quickpic"),
        //        new Car(107596, 389, "IVECO Trakker AD180T27W 4x4 F-C Exp", "Trakker AD180T27W 4x4 F-C Exp",
        //            "Freight Carrier", "Diesel", "XHV", "Man", false, "/images/Lightstone-auto-car.png",
        //            "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107597, 785, "TATA SK 407T 2T 4x2 Tipper", "SK 407T 2T 4x2 Tipper", "Tipper", "Diesel", "MCV",
        //            "Man", false, "http://www.rgt.co.za/photos/TATA/107597_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TATA/107597_1_S.jpg", "Quickpic"),
        //        new Car(107598, 61, "BMW M3 Coupe", "M3 Coupe", "Coupe", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/BMW/107598_1_P.jpg", "http://www.rgt.co.za/photos/BMW/107598_1_S.jpg",
        //            "Quickpic"),
        //        new Car(107600, 94, "CHEVROLET Captiva 2.4 LT AWD 5-dr", "Captiva 2.4 LT AWD 5-dr", "SUV", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/CHEVROLET/107600_1_P.jpg",
        //            "http://www.rgt.co.za/photos/CHEVROLET/107600_1_S.jpg", "Motorpic"),
        //        new Car(107601, 94, "CHEVROLET Captiva 3.2 LTZ AWD 5-dr AT", "Captiva 3.2 LTZ AWD 5-dr AT", "SUV",
        //            "Petrol", "PAS", "Auto", false, "http://www.rgt.co.za/photos/CHEVROLET/107601_1_P.jpg",
        //            "http://www.rgt.co.za/photos/CHEVROLET/107601_1_S.jpg", "Motorpic"),
        //        new Car(107602, 94, "CHEVROLET Captiva 2.0D LTZ AWD Dsl 5-dr", "Captiva 2.0D LTZ AWD Dsl 5-dr", "SUV",
        //            "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/CHEVROLET/107602_1_P.jpg",
        //            "http://www.rgt.co.za/photos/CHEVROLET/107602_1_S.jpg", "Motorpic"),
        //        new Car(107603, 875, "VOLKSWAGEN Golf 5 2.0 TDi Sportline 5-dr Dsl MY08",
        //            "Golf 5 2.0 TDi Sportline 5-dr Dsl MY08", "Hatch (5-dr)", "Diesel", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107603_1_P.jpg",
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107603_1_S.jpg", "Motorpic"),
        //        new Car(107604, 875, "VOLKSWAGEN Golf 5 2.0 FSi Sportline 5-dr MY08",
        //            "Golf 5 2.0 FSi Sportline 5-dr MY08", "Hatch (5-dr)", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107604_1_P.jpg",
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107604_1_S.jpg", "Motorpic"),
        //        new Car(107605, 563, "MERCEDES Viano Ambiente 3.0 CDi Dsl 7-s MPV", "Viano Ambiente 3.0 CDi Dsl 7-s MPV",
        //            "MPV", "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/MERCEDES/107605_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MERCEDES/107605_1_S.jpg", "Quickpic"),
        //        new Car(107606, 563, "MERCEDES Viano Trend 2.2 CDi Dsl 7-s MPV", "Viano Trend 2.2 CDi Dsl 7-s MPV",
        //            "MPV", "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/MERCEDES/107606_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MERCEDES/107606_1_S.jpg", "Quickpic"),
        //        new Car(107607, 429, "LAND ROVER Defender 110 Puma 2.4 D Ch-Cab 4x4 Dsl",
        //            "Defender 110 Puma 2.4 D Ch-Cab 4x4 Dsl", "Double Cab Pick-Up", "Diesel", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/LAND ROVER/107607_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LAND ROVER/107607_1_S.jpg", "Quickpic"),
        //        new Car(107608, 106, "CHRYSLER 300C 5.7 Touring AT", "300C 5.7 Touring AT", "Estate", "Petrol", "PAS",
        //            "Auto", false, "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107609, 903, "VOLKSWAGEN Touareg 3.6 FSi 4x4 Tiptronic", "Touareg 3.6 FSi 4x4 Tiptronic", "SUV",
        //            "Petrol", "PAS", "Elec", false, "http://www.rgt.co.za/photos/VOLKSWAGEN/107609_1_P.jpg",
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107609_1_S.jpg", "Motorpic"),
        //        new Car(107610, 553, "MERCEDES ML 500 V8 4x4 7-sp G-Tronic", "ML 500 V8 4x4 7-sp G-Tronic", "SUV",
        //            "Petrol", "PAS", "Elec", false, "http://www.rgt.co.za/photos/MERCEDES/107610_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MERCEDES/107610_1_S.jpg", "Quickpic"),
        //        new Car(107611, 429, "LAND ROVER Defender 110 Puma 2.4 D HT 4x4 Dsl PU",
        //            "Defender 110 Puma 2.4 D HT 4x4 Dsl PU", "Single Cab Pick-Up", "Diesel", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/LAND ROVER/107611_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LAND ROVER/107611_1_S.jpg", "Quickpic"),
        //        new Car(107612, 429, "LAND ROVER Defender 110 Puma 2.4 D 4x4 Dsl PU",
        //            "Defender 110 Puma 2.4 D 4x4 Dsl PU", "Single Cab Pick-Up", "Diesel", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/LAND ROVER/107612_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LAND ROVER/107612_1_S.jpg", "Quickpic"),
        //        new Car(107613, 429, "LAND ROVER Defender 110 Puma 2.4 D Cr-Cab 4x4 Dsl",
        //            "Defender 110 Puma 2.4 D Cr-Cab 4x4 Dsl", "Double Cab Pick-Up", "Diesel", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/LAND ROVER/107613_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LAND ROVER/107613_1_S.jpg", "Quickpic"),
        //        new Car(107614, 429, "LAND ROVER Defender 130 Puma 2.4 D Ch-Cab 4x4 Dsl",
        //            "Defender 130 Puma 2.4 D Ch-Cab 4x4 Dsl", "Double Cab Pick-Up", "Diesel", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/LAND ROVER/107614_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LAND ROVER/107614_1_S.jpg", "Quickpic"),
        //        new Car(107615, 429, "LAND ROVER Defender 130 Puma 2.4 D Cr-Cab 4x4 HCPU Dsl",
        //            "Defender 130 Puma 2.4 D Cr-Cab 4x4 HCPU Dsl", "Double Cab Pick-Up", "Diesel", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/LAND ROVER/107615_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LAND ROVER/107615_1_S.jpg", "Quickpic"),
        //        new Car(107616, 617, "NISSAN Qashqai 1.6 Visia 5-dr", "Qashqai 1.6 Visia 5-dr", "Crossover", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/NISSAN/107616_1_P.jpg",
        //            "http://www.rgt.co.za/photos/NISSAN/107616_1_S.jpg", "Quickpic"),
        //        new Car(107617, 617, "NISSAN Qashqai 1.6 Acenta 5-dr", "Qashqai 1.6 Acenta 5-dr", "Crossover", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/NISSAN/107617_1_P.jpg",
        //            "http://www.rgt.co.za/photos/NISSAN/107617_1_S.jpg", "Quickpic"),
        //        new Car(107618, 617, "NISSAN Qashqai 2.0 Acenta 5-dr", "Qashqai 2.0 Acenta 5-dr", "Crossover", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/NISSAN/107618_1_P.jpg",
        //            "http://www.rgt.co.za/photos/NISSAN/107618_1_S.jpg", "Quickpic"),
        //        new Car(107619, 612, "NISSAN Pathfinder 2.5 DCi LE 4x4 Dsl MY08 AT",
        //            "Pathfinder 2.5 DCi LE 4x4 Dsl MY08 AT", "SUV", "Diesel", "PAS", "Elec", false,
        //            "http://www.rgt.co.za/photos/NISSAN/107619_1_P.jpg",
        //            "http://www.rgt.co.za/photos/NISSAN/107619_1_S.jpg", "Manufacturer"),
        //        new Car(107620, 846, "VOLVO FH13M 480 S/R SC 6x4 T-T", "FH13M 480 S/R SC 6x4 T-T", "Truck-Tractor",
        //            "Diesel", "XHV", "Man", false, "/images/Lightstone-auto-car.png",
        //            "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107621, 674, "PORSCHE 987 Boxster 2.7 Roadster", "987 Boxster 2.7 Roadster", "Cabriolet",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/PORSCHE/107621_1_P.jpg",
        //            "http://www.rgt.co.za/photos/PORSCHE/107621_1_S.jpg", "Manufacturer"),
        //        new Car(107622, 674, "PORSCHE 987 Boxster 2.7 Roadster Tiptronic", "987 Boxster 2.7 Roadster Tiptronic",
        //            "Cabriolet", "Petrol", "PAS", "Elec", false, "http://www.rgt.co.za/photos/PORSCHE/107622_1_P.jpg",
        //            "http://www.rgt.co.za/photos/PORSCHE/107622_1_S.jpg", "Manufacturer"),
        //        new Car(107623, 674, "PORSCHE 987 Boxster S 3.4 Roadster", "987 Boxster S 3.4 Roadster", "Cabriolet",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/PORSCHE/107623_1_P.jpg",
        //            "http://www.rgt.co.za/photos/PORSCHE/107623_1_S.jpg", "Manufacturer"),
        //        new Car(107624, 674, "PORSCHE 987 Boxster S 3.4 Roadster Tiptronic",
        //            "987 Boxster S 3.4 Roadster Tiptronic", "Cabriolet", "Petrol", "PAS", "Elec", false,
        //            "http://www.rgt.co.za/photos/PORSCHE/107624_1_P.jpg",
        //            "http://www.rgt.co.za/photos/PORSCHE/107624_1_S.jpg", "Manufacturer"),
        //        new Car(107625, 675, "PORSCHE Cayenne 3.6 V6 4x4", "Cayenne 3.6 V6 4x4", "SUV", "Petrol", "PAS", "Man",
        //            false, "http://www.rgt.co.za/photos/PORSCHE/107625_1_P.jpg",
        //            "http://www.rgt.co.za/photos/PORSCHE/107625_1_S.jpg", "Manufacturer"),
        //        new Car(107626, 675, "PORSCHE Cayenne 3.6 V6 4x4 Tiptronic", "Cayenne 3.6 V6 4x4 Tiptronic", "SUV",
        //            "Petrol", "PAS", "Elec", false, "http://www.rgt.co.za/photos/PORSCHE/107626_1_P.jpg",
        //            "http://www.rgt.co.za/photos/PORSCHE/107626_1_S.jpg", "Manufacturer"),
        //        new Car(107627, 675, "PORSCHE Cayenne S 4.8 V8 4x4", "Cayenne S 4.8 V8 4x4", "SUV", "Petrol", "PAS",
        //            "Man", false, "http://www.rgt.co.za/photos/PORSCHE/107627_1_P.jpg",
        //            "http://www.rgt.co.za/photos/PORSCHE/107627_1_S.jpg", "Manufacturer"),
        //        new Car(107628, 675, "PORSCHE Cayenne S 4.8 V8 4x4 Tiptronic", "Cayenne S 4.8 V8 4x4 Tiptronic", "SUV",
        //            "Petrol", "PAS", "Elec", false, "http://www.rgt.co.za/photos/PORSCHE/107628_1_P.jpg",
        //            "http://www.rgt.co.za/photos/PORSCHE/107628_1_S.jpg", "Manufacturer"),
        //        new Car(107629, 675, "PORSCHE Cayenne Turbo 4.8 V8 4x4 Tiptronic", "Cayenne Turbo 4.8 V8 4x4 Tiptronic",
        //            "SUV", "Petrol", "PAS", "Elec", false, "http://www.rgt.co.za/photos/PORSCHE/107629_1_P.jpg",
        //            "http://www.rgt.co.za/photos/PORSCHE/107629_1_S.jpg", "Manufacturer"),
        //        new Car(107630, 414, "KIA K2700 Workhorse Ch-Cab Dsl PU", "K2700 Workhorse Ch-Cab Dsl PU",
        //            "Single Cab Pick-Up", "Diesel", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/KIA/107630_1_P.jpg", "http://www.rgt.co.za/photos/KIA/107630_1_S.jpg",
        //            "Quickpic"),
        //        new Car(107631, 581, "MITSUBISHI Lancer 1.5", "Lancer 1.5", "Sedan", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/MITSUBISHI/107631_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MITSUBISHI/107631_1_S.jpg", "Quickpic"),
        //        new Car(107632, 581, "MITSUBISHI Lancer 2.0 GLS", "Lancer 2.0 GLS", "Sedan", "Petrol", "PAS", "Man",
        //            false, "http://www.rgt.co.za/photos/MITSUBISHI/107632_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MITSUBISHI/107632_1_S.jpg", "Manufacturer"),
        //        new Car(107633, 495, "MAN TGM 15.240 BLS 4x2 T-T", "TGM 15.240 BLS 4x2 T-T", "Truck-Tractor", "Diesel",
        //            "HCV", "Man", false, "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png",
        //            "Lightstone"),
        //        new Car(107634, 673, "PORSCHE 911/997 GT2 Coupe", "911/997 GT2 Coupe", "Coupe", "Petrol", "PAS", "Man",
        //            false, "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107635, 266, "FORD Ikon 1.4 Ambiente", "Ikon 1.4 Ambiente", "Sedan", "Petrol", "PAS", "Man",
        //            false, "http://www.rgt.co.za/photos/FORD/107635_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FORD/107635_1_S.jpg", "Quickpic"),
        //        new Car(107636, 675, "PORSCHE Cayenne GTS 4.8 4x4", "Cayenne GTS 4.8 4x4", "SUV", "Petrol", "PAS", "Man",
        //            false, "http://www.rgt.co.za/photos/PORSCHE/107636_1_P.jpg",
        //            "http://www.rgt.co.za/photos/PORSCHE/107636_1_S.jpg", "Manufacturer"),
        //        new Car(107637, 866, "VOLKSWAGEN CitiGolf 1.8 5-dr", "CitiGolf 1.8 5-dr", "Hatch (5-dr)", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/VOLKSWAGEN/107637_1_P.jpg",
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107637_1_S.jpg", "Motorpic"),
        //        new Car(107638, 904, "VOLKSWAGEN Touran 1.6 Trendline MPV", "Touran 1.6 Trendline MPV", "MPV", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/VOLKSWAGEN/107638_1_P.jpg",
        //            "http://www.rgt.co.za/photos/VOLKSWAGEN/107638_1_S.jpg", "Motorpic"),
        //        new Car(107639, 398, "JAGUAR XJ6 3.0 Sovereign AT MY07", "XJ6 3.0 Sovereign AT MY07", "Sedan", "Petrol",
        //            "PAS", "Elec", false, "http://www.rgt.co.za/photos/JAGUAR/107639_1_P.jpg",
        //            "http://www.rgt.co.za/photos/JAGUAR/107639_1_S.jpg", "Quickpic"),
        //        new Car(107640, 398, "JAGUAR XJ8 4.2 Sovereign AT MY07", "XJ8 4.2 Sovereign AT MY07", "Sedan", "Petrol",
        //            "PAS", "Elec", false, "http://www.rgt.co.za/photos/JAGUAR/107640_1_P.jpg",
        //            "http://www.rgt.co.za/photos/JAGUAR/107640_1_S.jpg", "Quickpic"),
        //        new Car(107641, 398, "JAGUAR XJ8 4.2 Sovereign LWB AT MY07", "XJ8 4.2 Sovereign LWB AT MY07", "Sedan",
        //            "Petrol", "PAS", "Elec", false, "http://www.rgt.co.za/photos/JAGUAR/107641_1_P.jpg",
        //            "http://www.rgt.co.za/photos/JAGUAR/107641_1_S.jpg", "Quickpic"),
        //        new Car(107643, 398, "JAGUAR XJR 4.2 Super AT MY07", "XJR 4.2 Super AT MY07", "Sedan", "Petrol", "PAS",
        //            "Elec", false, "http://www.rgt.co.za/photos/JAGUAR/107643_1_P.jpg",
        //            "http://www.rgt.co.za/photos/JAGUAR/107643_1_S.jpg", "Quickpic"),
        //        new Car(107644, 447, "LEXUS IS 250 MY07", "IS 250 MY07", "Sedan", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/LEXUS/107644_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LEXUS/107644_1_S.jpg", "Quickpic"),
        //        new Car(107645, 447, "LEXUS IS 250 MY07 AT", "IS 250 MY07 AT", "Sedan", "Petrol", "PAS", "Elec", false,
        //            "http://www.rgt.co.za/photos/LEXUS/107645_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LEXUS/107645_1_S.jpg", "Quickpic"),
        //        new Car(107646, 447, "LEXUS IS 250 SE MY07", "IS 250 SE MY07", "Sedan", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/LEXUS/107646_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LEXUS/107646_1_S.jpg", "Quickpic"),
        //        new Car(107647, 447, "LEXUS IS 250 SE MY07 AT", "IS 250 SE MY07 AT", "Sedan", "Petrol", "PAS", "Elec",
        //            false, "http://www.rgt.co.za/photos/LEXUS/107647_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LEXUS/107647_1_S.jpg", "Quickpic"),
        //        new Car(107648, 750, "SSANGYONG Kyron 270 XDi Dsl T-Tronic", "Kyron 270 XDi Dsl T-Tronic", "SUV",
        //            "Diesel", "PAS", "Elec", false, "http://www.rgt.co.za/photos/SSANGYONG/107648_1_P.jpg",
        //            "http://www.rgt.co.za/photos/SSANGYONG/107648_1_S.jpg", "Quickpic"),
        //        new Car(107649, 754, "SSANGYONG Stavic SV270 XDi Low spec MPV Dsl", "Stavic SV270 XDi Low spec MPV Dsl",
        //            "MPV", "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/SSANGYONG/107649_1_P.jpg",
        //            "http://www.rgt.co.za/photos/SSANGYONG/107649_1_S.jpg", "Quickpic"),
        //        new Car(107650, 429, "LAND ROVER Defender 110 Puma 2.4 D Cr-Cab HCPU 4x4 Dsl",
        //            "Defender 110 Puma 2.4 D Cr-Cab HCPU 4x4 Dsl", "Double Cab Pick-Up", "Diesel", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/LAND ROVER/107650_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LAND ROVER/107650_1_S.jpg", "Quickpic"),
        //        new Car(107651, 431, "LAND ROVER Discovery 3 2.7 TDV6 HSE 4x4 Dsl AT Leather MY08",
        //            "Discovery 3 2.7 TDV6 HSE 4x4 Dsl AT Leather MY08", "SUV", "Diesel", "PAS", "Auto", false,
        //            "http://www.rgt.co.za/photos/LAND ROVER/107651_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LAND ROVER/107651_1_S.jpg", "Quickpic"),
        //        new Car(107652, 431, "LAND ROVER Discovery 3 4.4 V8 HSE 4x4 AT Leather MY08",
        //            "Discovery 3 4.4 V8 HSE 4x4 AT Leather MY08", "SUV", "Petrol", "PAS", "Auto", false,
        //            "http://www.rgt.co.za/photos/LAND ROVER/107652_1_P.jpg",
        //            "http://www.rgt.co.za/photos/LAND ROVER/107652_1_S.jpg", "Quickpic"),
        //        new Car(107653, 742, "SEAT Leon 2.0 TFSi Cupra 5-dr", "Leon 2.0 TFSi Cupra 5-dr", "Hatch (5-dr)",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/SEAT/107653_1_P.jpg",
        //            "http://www.rgt.co.za/photos/SEAT/107653_1_S.jpg", "Motorpic"),
        //        new Car(107654, 843, "VOLVO C30 1.6 3-dr", "C30 1.6 3-dr", "Hatch (3-dr)", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/VOLVO/107654_1_P.jpg",
        //            "http://www.rgt.co.za/photos/VOLVO/107654_1_S.jpg", "Quickpic"),
        //        new Car(107655, 843, "VOLVO C30 1.8 3-dr", "C30 1.8 3-dr", "Hatch (3-dr)", "Petrol", "PAS", "Man", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107656, 266, "FORD Ikon 1.4 TDCi Trend Dsl", "Ikon 1.4 TDCi Trend Dsl", "Sedan", "Diesel", "PAS",
        //            "Man", false, "http://www.rgt.co.za/photos/FORD/107656_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FORD/107656_1_S.jpg", "Quickpic"),
        //        new Car(107657, 266, "FORD Ikon 1.6 Trend", "Ikon 1.6 Trend", "Sedan", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/FORD/107657_1_P.jpg", "http://www.rgt.co.za/photos/FORD/107657_1_S.jpg",
        //            "Quickpic"),
        //        new Car(107658, 61, "BMW 320i Exp MY07", "320i Exp MY07", "Sedan", "Petrol", "PAS", "Man", false,
        //            "/images/Lightstone-auto-car.png", "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107659, 660, "PEUGEOT 407 Coupe 2.2", "407 Coupe 2.2", "Coupe", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/PEUGEOT/107659_1_P.jpg",
        //            "http://www.rgt.co.za/photos/PEUGEOT/107659_1_S.jpg", "Motorpic"),
        //        new Car(107660, 612, "NISSAN Pathfinder 4.0 4x4 Tiptronic MY08", "Pathfinder 4.0 4x4 Tiptronic MY08",
        //            "SUV", "Petrol", "PAS", "Elec", false, "http://www.rgt.co.za/photos/NISSAN/107660_1_P.jpg",
        //            "http://www.rgt.co.za/photos/NISSAN/107660_1_S.jpg", "Manufacturer"),
        //        new Car(107661, 612, "NISSAN Pathfinder 2.5 DCi LE 4x4 Dsl MY08", "Pathfinder 2.5 DCi LE 4x4 Dsl MY08",
        //            "SUV", "Diesel", "PAS", "Man", false, "http://www.rgt.co.za/photos/NISSAN/107661_1_P.jpg",
        //            "http://www.rgt.co.za/photos/NISSAN/107661_1_S.jpg", "Manufacturer"),
        //        new Car(107662, 387, "IVECO Stralis AT260S43YPS 6x2 F-C", "Stralis AT260S43YPS 6x2 F-C",
        //            "Freight Carrier", "Diesel", "XHV", "Man", false, "/images/Lightstone-auto-car.png",
        //            "/images/Lightstone-auto-car-s.png", "Lightstone"),
        //        new Car(107663, 389, "IVECO Trakker AD380T42 6x4 F-C", "Trakker AD380T42 6x4 F-C", "Freight Carrier",
        //            "Diesel", "XHV", "Man", false, "http://www.rgt.co.za/photos/IVECO/107663_1_P.jpg",
        //            "http://www.rgt.co.za/photos/IVECO/107663_1_S.jpg", "Manufacturer"),
        //        new Car(107664, 235, "FIAT Ducato 2.3 V-MH1 Vetrato P-Van Dsl", "Ducato 2.3 V-MH1 Vetrato P-Van Dsl",
        //            "Panel Van", "Diesel", "MCV", "Man", false, "http://www.rgt.co.za/photos/FIAT/107664_1_P.jpg",
        //            "http://www.rgt.co.za/photos/FIAT/107664_1_S.jpg", "Quickpic"),
        //        new Car(107665, 607, "NISSAN Navara 4.0i V6 D-Cab Hi-Rider PU MY08",
        //            "Navara 4.0i V6 D-Cab Hi-Rider PU MY08", "Double Cab Pick-Up", "Petrol", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/NISSAN/107665_1_P.jpg",
        //            "http://www.rgt.co.za/photos/NISSAN/107665_1_S.jpg", "Quickpic"),
        //        new Car(107666, 607, "NISSAN Navara 2.5 TDi D-Cab Hi-Rider AT Dsl PU MY08",
        //            "Navara 2.5 TDi D-Cab Hi-Rider AT Dsl PU MY08", "Double Cab Pick-Up", "Diesel", "LCV", "Auto", false,
        //            "http://www.rgt.co.za/photos/NISSAN/107666_1_P.jpg",
        //            "http://www.rgt.co.za/photos/NISSAN/107666_1_S.jpg", "Quickpic"),
        //        new Car(107667, 607, "NISSAN Navara 2.5 TDi D-Cab 4x4 Dsl PU MY08",
        //            "Navara 2.5 TDi D-Cab 4x4 Dsl PU MY08", "Double Cab Pick-Up", "Diesel", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/NISSAN/107667_1_P.jpg",
        //            "http://www.rgt.co.za/photos/NISSAN/107667_1_S.jpg", "Quickpic"),
        //        new Car(107668, 641, "OPEL Vivaro 1.9 CDTi Opulent P-Van Dsl", "Vivaro 1.9 CDTi Opulent P-Van Dsl",
        //            "Panel Van", "Diesel", "LCV", "Man", false, "http://www.rgt.co.za/photos/OPEL/107668_1_P.jpg",
        //            "http://www.rgt.co.za/photos/OPEL/107668_1_S.jpg", "Quickpic"),
        //        new Car(107669, 641, "OPEL Vivaro 2.0 Opulent P-Van", "Vivaro 2.0 Opulent P-Van", "Panel Van", "Petrol",
        //            "LCV", "Man", false, "http://www.rgt.co.za/photos/OPEL/107669_1_P.jpg",
        //            "http://www.rgt.co.za/photos/OPEL/107669_1_S.jpg", "Quickpic"),
        //        new Car(107670, 60, "BMW 116i Hatch 3-dr MY07", "116i Hatch 3-dr MY07", "Hatch (3-dr)", "Petrol", "PAS",
        //            "Man", false, "http://www.rgt.co.za/photos/BMW/107670_1_P.jpg",
        //            "http://www.rgt.co.za/photos/BMW/107670_1_S.jpg", "Quickpic"),
        //        new Car(107671, 630, "OPEL Combo 1.4 3-dr AC P-Van", "Combo 1.4 3-dr AC P-Van", "Panel Van", "Petrol",
        //            "LCV", "Man", false, "http://www.rgt.co.za/photos/OPEL/107671_1_P.jpg",
        //            "http://www.rgt.co.za/photos/OPEL/107671_1_S.jpg", "Quickpic"),
        //        new Car(107672, 61, "BMW 320d Dsl MY07", "320d Dsl MY07", "Sedan", "Diesel", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/BMW/107672_1_P.jpg", "http://www.rgt.co.za/photos/BMW/107672_1_S.jpg",
        //            "Manufacturer"),
        //        new Car(107673, 61, "BMW 320d Dsl MY07 AT", "320d Dsl MY07 AT", "Sedan", "Diesel", "PAS", "Elec", false,
        //            "http://www.rgt.co.za/photos/BMW/107673_1_P.jpg", "http://www.rgt.co.za/photos/BMW/107673_1_S.jpg",
        //            "Manufacturer"),
        //        new Car(107674, 52, "AUDI R8 Quattro 4.2 FSi Coupe", "R8 Quattro 4.2 FSi Coupe", "Coupe", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/AUDI/107674_1_P.jpg",
        //            "http://www.rgt.co.za/photos/AUDI/107674_1_S.jpg", "Motorpic"),
        //        new Car(107675, 52, "AUDI R8 Quattro 4.2 FSi Coupe R-Tronic", "R8 Quattro 4.2 FSi Coupe R-Tronic",
        //            "Coupe", "Petrol", "PAS", "Elec", false, "http://www.rgt.co.za/photos/AUDI/107675_1_P.jpg",
        //            "http://www.rgt.co.za/photos/AUDI/107675_1_S.jpg", "Motorpic"),
        //        new Car(107676, 819, "TOYOTA Landcruiser Prado 3.0 DT 4x4 8-s Dsl MY07",
        //            "Landcruiser Prado 3.0 DT 4x4 8-s Dsl MY07", "SUV", "Diesel", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/TOYOTA/107676_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107676_1_S.jpg", "Quickpic"),
        //        new Car(107677, 819, "TOYOTA Landcruiser Prado 3.0 DT VX 4x4 8-s Dsl AT MY07",
        //            "Landcruiser Prado 3.0 DT VX 4x4 8-s Dsl AT MY07", "SUV", "Diesel", "PAS", "Auto", false,
        //            "http://www.rgt.co.za/photos/TOYOTA/107677_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107677_1_S.jpg", "Quickpic"),
        //        new Car(107678, 819, "TOYOTA Landcruiser Prado 4.0 VX 4x4 AT MY07",
        //            "Landcruiser Prado 4.0 VX 4x4 AT MY07", "SUV", "Petrol", "PAS", "Auto", false,
        //            "http://www.rgt.co.za/photos/TOYOTA/107678_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107678_1_S.jpg", "Quickpic"),
        //        new Car(107681, 505, "MAZDA Mazda2 1.3 Active 5-dr", "Mazda2 1.3 Active 5-dr", "Hatch (5-dr)", "Petrol",
        //            "PAS", "Man", false, "http://www.rgt.co.za/photos/MAZDA/107681_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MAZDA/107681_1_S.jpg", "Quickpic"),
        //        new Car(107682, 505, "MAZDA Mazda2 1.3 Dynamic 5-dr", "Mazda2 1.3 Dynamic 5-dr", "Hatch (5-dr)",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/MAZDA/107682_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MAZDA/107682_1_S.jpg", "Quickpic"),
        //        new Car(107683, 505, "MAZDA Mazda2 1.5 Dynamic 5-dr", "Mazda2 1.5 Dynamic 5-dr", "Hatch (5-dr)",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/MAZDA/107683_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MAZDA/107683_1_S.jpg", "Quickpic"),
        //        new Car(107684, 505, "MAZDA Mazda2 1.5 Individual 5-dr", "Mazda2 1.5 Individual 5-dr", "Hatch (5-dr)",
        //            "Petrol", "PAS", "Man", false, "http://www.rgt.co.za/photos/MAZDA/107684_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MAZDA/107684_1_S.jpg", "Quickpic"),
        //        new Car(107685, 540, "MERCEDES B170 MPV CVT", "B170 MPV CVT", "MPV", "Petrol", "PAS", "Elec", false,
        //            "http://www.rgt.co.za/photos/MERCEDES/107685_1_P.jpg",
        //            "http://www.rgt.co.za/photos/MERCEDES/107685_1_S.jpg", "Motorpic"),
        //        new Car(107686, 61, "BMW 320i Start MY07", "320i Start MY07", "Sedan", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/BMW/107686_1_P.jpg", "http://www.rgt.co.za/photos/BMW/107686_1_S.jpg",
        //            "Manufacturer"),
        //        new Car(107687, 61, "BMW 320i Start MY07 AT", "320i Start MY07 AT", "Sedan", "Petrol", "PAS", "Elec",
        //            false, "http://www.rgt.co.za/photos/BMW/107687_1_P.jpg",
        //            "http://www.rgt.co.za/photos/BMW/107687_1_S.jpg", "Manufacturer"),
        //        new Car(107688, 61, "BMW 320d Dsl Start MY07", "320d Dsl Start MY07", "Sedan", "Diesel", "PAS", "Man",
        //            false, "http://www.rgt.co.za/photos/BMW/107688_1_P.jpg",
        //            "http://www.rgt.co.za/photos/BMW/107688_1_S.jpg", "Manufacturer"),
        //        new Car(107689, 61, "BMW 320d Dsl Start MY07 AT", "320d Dsl Start MY07 AT", "Sedan", "Diesel", "PAS",
        //            "Elec", false, "http://www.rgt.co.za/photos/BMW/107689_1_P.jpg",
        //            "http://www.rgt.co.za/photos/BMW/107689_1_S.jpg", "Manufacturer"),
        //        new Car(107690, 61, "BMW 320i MY07", "320i MY07", "Sedan", "Petrol", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/BMW/107690_1_P.jpg", "http://www.rgt.co.za/photos/BMW/107690_1_S.jpg",
        //            "Manufacturer"),
        //        new Car(107691, 61, "BMW 320i MY07 AT", "320i MY07 AT", "Sedan", "Petrol", "PAS", "Elec", false,
        //            "http://www.rgt.co.za/photos/BMW/107691_1_P.jpg", "http://www.rgt.co.za/photos/BMW/107691_1_S.jpg",
        //            "Manufacturer"),
        //        new Car(107692, 61, "BMW 330d Dsl MY07", "330d Dsl MY07", "Sedan", "Diesel", "PAS", "Man", false,
        //            "http://www.rgt.co.za/photos/BMW/107692_1_P.jpg", "http://www.rgt.co.za/photos/BMW/107692_1_S.jpg",
        //            "Manufacturer"),
        //        new Car(107693, 61, "BMW 330d Dsl MY07 AT", "330d Dsl MY07 AT", "Sedan", "Diesel", "PAS", "Elec", false,
        //            "http://www.rgt.co.za/photos/BMW/107693_1_P.jpg", "http://www.rgt.co.za/photos/BMW/107693_1_S.jpg",
        //            "Manufacturer"),
        //        new Car(107694, 807, "TOYOTA Hilux 2.5 SRX D-4D D-Cab 4x4 Dsl PU MY07",
        //            "Hilux 2.5 SRX D-4D D-Cab 4x4 Dsl PU MY07", "Double Cab Pick-Up", "Diesel", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/TOYOTA/107694_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107694_1_S.jpg", "Manufacturer"),
        //        new Car(107695, 807, "TOYOTA Hilux 2.7 SRX VVT-i LWB 4x4 PU MY07", "Hilux 2.7 SRX VVT-i LWB 4x4 PU MY07",
        //            "Single Cab Pick-Up", "Petrol", "LCV", "Man", false,
        //            "http://www.rgt.co.za/photos/TOYOTA/107695_1_P.jpg",
        //            "http://www.rgt.co.za/photos/TOYOTA/107695_1_S.jpg", "Manufacturer"),
        //    };
        //}
    }
}
