using System.Collections.Generic;
using Lace.Domain.DataProviders.Lightstone.Core.Models;
namespace Lace.Test.Helper.Mothers.Sources.Lightstone
{
    public class MakeData
    {
        public static IEnumerable<Make> ForAllMakes()
        {
            return new List<Make>()
            {
                new Make(1, "AAD"),
                new Make(2, "ABARTH"),
                new Make(3, "AFRICAR"),
                new Make(4, "ALFA ROMEO"),
                new Make(5, "ASIAWING"),
                new Make(6, "ASTON MARTIN"),
                new Make(7, "AUDI"),
                new Make(8, "BENTLEY"),
                new Make(9, "BMC"),
                new Make(10, "BMW"),
                new Make(11, "CADILLAC"),
                new Make(12, "CAM"),
                new Make(13, "CHANA"),
                new Make(14, "CHANGAN"),
                new Make(15, "CHERY"),
                new Make(16, "CHEVROLET"),
                new Make(17, "CHRYSLER"),
                new Make(18, "CITROEN"),
                new Make(19, "CMC"),
                new Make(20, "DACIA"),
                new Make(21, "DAEWOO"),
                new Make(22, "DAF"),
                new Make(23, "DAIHATSU"),
                new Make(24, "DFM"),
                new Make(25, "DFSK"),
                new Make(26, "DODGE"),
                new Make(27, "ERF"),
                new Make(28, "FAW"),
                new Make(29, "FERRARI"),
                new Make(30, "FIAT"),
                new Make(31, "FORCE MOTORS"),
                new Make(32, "FORD"),
                new Make(33, "FOTON"),
                new Make(34, "FREIGHTLINER"),
                new Make(35, "FUDI"),
                new Make(36, "FUSO"),
                new Make(37, "GAZ"),
                new Make(38, "GEELY"),
                new Make(39, "GONOW"),
                new Make(40, "GWM"),
                new Make(41, "HAFEI"),
                new Make(42, "HINO"),
                new Make(43, "HONDA"),
                new Make(44, "HUMMER"),
                new Make(45, "HYUNDAI"),
                new Make(46, "INFINITI"),
                new Make(47, "INTERNATIONAL"),
                new Make(48, "ISUZU"),
                new Make(49, "IVECO"),
                new Make(50, "JAGUAR"),
                new Make(51, "JEEP"),
                new Make(52, "JMC"),
                new Make(53, "KIA"),
                new Make(54, "LADA"),
                new Make(55, "LAMBORGHINI"),
                new Make(56, "LAND ROVER"),
                new Make(57, "LEXUS"),
                new Make(58, "LOTUS"),
                new Make(59, "MACK"),
                new Make(60, "MAHINDRA"),
                new Make(61, "MAN"),
                new Make(62, "MASERATI"),
                new Make(63, "MAXUS"),
                new Make(64, "MAYBACH"),
                new Make(65, "MAZDA"),
                new Make(66, "MCLAREN"),
                new Make(67, "MEIYA"),
                new Make(68, "MERCEDES"),
                new Make(69, "MG"),
                new Make(70, "MINI"),
                new Make(71, "MITSUBISHI"),
                new Make(72, "MORGAN"),
                new Make(73, "NISSAN"),
                new Make(74, "OPEL"),
                new Make(0, "OVERALL"),
                new Make(75, "PETERBILT"),
                new Make(76, "PEUGEOT"),
                new Make(77, "POLARSUN"),
                new Make(78, "PORSCHE"),
                new Make(79, "POWERSTAR"),
                new Make(80, "PROTON"),
                new Make(81, "RENAULT"),
                new Make(82, "ROLLS-ROYCE"),
                new Make(83, "ROVER"),
                new Make(84, "SAAB"),
                new Make(85, "SCANIA"),
                new Make(86, "SEAT"),
                new Make(87, "SMART"),
                new Make(88, "SOYAT"),
                new Make(89, "SSANGYONG"),
                new Make(90, "SUBARU"),
                new Make(91, "SUZUKI"),
                new Make(92, "TATA"),
                new Make(93, "TOYOTA"),
                new Make(94, "TVR"),
                new Make(95, "UD TRUCKS"),
                new Make(96, "VDL"),
                new Make(97, "VOLKSWAGEN"),
                new Make(98, "VOLVO"),
                new Make(99, "WESTERN STAR"),
                new Make(100, "ZOTYE")
            };
        }
    }
}
