using System.Collections.Generic;
using Lace.Source.Lightstone.Models;

namespace Lace.Test.Helper.Mothers.Sources.Lightstone
{
    public class MunicipalityData
    {
        public static IEnumerable<Municipality> ForAllMuncipalities()
        {
            return new List<Municipality>()
            {
                new Municipality(1, "//KHARA HAIS"),
                new Municipality(2, "ABAQULUSI"),
                new Municipality(3, "AMAHLATHI"),
                new Municipality(4, "BA-PHALABORWA"),
                new Municipality(5, "BEAUFORT WEST"),
                new Municipality(6, "BELA-BELA"),
                new Municipality(7, "BERGRIVIER"),
                new Municipality(8, "BLUE CRANE ROUTE"),
                new Municipality(9, "BREEDE RIVER/WINELANDS"),
                new Municipality(10, "BREEDE VALLEY"),
                new Municipality(11, "BUFFALO CITY"),
                new Municipality(12, "CAMDEBOO"),
                new Municipality(13, "CAPE AGULHAS"),
                new Municipality(14, "CEDERBERG"),
                new Municipality(15, "CITY OF CAPE TOWN"),
                new Municipality(16, "CITY OF JOHANNESBURG"),
                new Municipality(17, "CITY OF MATLOSANA"),
                new Municipality(18, "CITY OF TSHWANE"),
                new Municipality(19, "DELMAS"),
                new Municipality(20, "DIHLABENG"),
                new Municipality(21, "DITSOBOTLA"),
                new Municipality(22, "DRAKENSTEIN"),
                new Municipality(23, "EDUMBE"),
                new Municipality(24, "EKURHULENI"),
                new Municipality(25, "ELIAS MOTSOALEDI"),
                new Municipality(26, "EMALAHLENI"),
                new Municipality(27, "EMFULENI"),
                new Municipality(28, "EMNAMBITHI/LADYSMITH"),
                new Municipality(29, "EMTHANJENI"),
                new Municipality(30, "ENDUMENI"),
                new Municipality(31, "ETHEKWINI"),
                new Municipality(32, "GA-SEGONYANA"),
                new Municipality(33, "GEORGE"),
                new Municipality(34, "GOVAN MBEKI"),
                new Municipality(35, "GREATER KOKSTAD"),
                new Municipality(36, "GREATER LETABA"),
                new Municipality(37, "GREATER TUBATSE"),
                new Municipality(38, "GREATER TZANEEN"),
                new Municipality(39, "HESSEQUA"),
                new Municipality(40, "HIBISCUS COAST"),
                new Municipality(41, "HLABISA"),
                new Municipality(42, "IMBABAZANE"),
                new Municipality(43, "INXUBA YETHEMBA"),
                new Municipality(44, "KNYSNA"),
                new Municipality(45, "KOUGA"),
                new Municipality(46, "KUNGWINI"),
                new Municipality(47, "KWADUKUZA"),
                new Municipality(48, "LEKWA"),
                new Municipality(49, "LEPHALALE"),
                new Municipality(50, "LESEDI"),
                new Municipality(51, "LOCAL MUNICIPALITY OF MADIBENG"),
                new Municipality(52, "LUKANJI"),
                new Municipality(53, "MAFIKENG"),
                new Municipality(54, "MAFUBE"),
                new Municipality(55, "MAKHADO"),
                new Municipality(56, "MALUTI A PHOFUNG"),
                new Municipality(57, "MAMUSA"),
                new Municipality(58, "MANGAUNG"),
                new Municipality(59, "MANTSOPA"),
                new Municipality(60, "MATATIELE"),
                new Municipality(61, "MATJHABENG"),
                new Municipality(62, "MATZIKAMA"),
                new Municipality(63, "MBOMBELA"),
                new Municipality(64, "MERAFONG CITY"),
                new Municipality(65, "MKHONDO"),
                new Municipality(66, "MODIMOLLE"),
                new Municipality(67, "MOGALAKWENA"),
                new Municipality(68, "MOGALE CITY"),
                new Municipality(69, "MOQHAKA"),
                new Municipality(70, "MOSES KOTANE"),
                new Municipality(71, "MOSSEL BAY"),
                new Municipality(72, "MSUKALIGWA"),
                new Municipality(73, "MUSINA"),
                new Municipality(74, "NALA"),
                new Municipality(75, "NALEDI"),
                new Municipality(76, "NAMA KHOI"),
                new Municipality(77, "NELSON MANDELA BAY"),
                new Municipality(78, "NEWCASTLE"),
                new Municipality(79, "NGWATHE"),
                new Municipality(80, "NKETOANA"),
                new Municipality(81, "NKOMAZI"),
                new Municipality(82, "NOKENG TSA TAEMANE"),
                new Municipality(0, "None"),
                new Municipality(83, "OUDTSHOORN"),
                new Municipality(84, "OVERSTRAND"),
                new Municipality(85, "PHOKWANE"),
                new Municipality(86, "PHUMELELA"),
                new Municipality(87, "POLOKWANE"),
                new Municipality(88, "RAMOTSHERE MOILOA"),
                new Municipality(89, "RANDFONTEIN"),
                new Municipality(90, "RUSTENBURG"),
                new Municipality(91, "SALDANHA BAY"),
                new Municipality(92, "SETSOTO"),
                new Municipality(93, "SOL PLAATJIE"),
                new Municipality(94, "STELLENBOSCH"),
                new Municipality(95, "STEVE TSHWETE"),
                new Municipality(96, "SWARTLAND"),
                new Municipality(97, "SWELLENDAM"),
                new Municipality(98, "THABA CHWEU"),
                new Municipality(99, "THABAZIMBI"),
                new Municipality(100, "THE MSUNDUZI"),
                new Municipality(101, "THEEWATERSKLOOF"),
                new Municipality(102, "TLOKWE CITY COUNCIL"),
                new Municipality(103, "TSANTSABANE"),
                new Municipality(104, "TSWAING"),
                new Municipality(105, "UMDONI"),
                new Municipality(106, "UMHLATHUZE"),
                new Municipality(107, "UMJINDI"),
                new Municipality(108, "UMLALAZI"),
                new Municipality(109, "UMNGENI"),
                new Municipality(110, "UMVOTI"),
                new Municipality(111, "UPHONGOLO"),
                new Municipality(112, "WESTONARIA"),
                new Municipality(113, "WITZENBERG"),
            };
        }
    }
}
