using Lace.Domain.Core.Contracts.DataProviders.Business;
using PackageBuilder.TestObjects.Builders.DataProviderResponses.LightstoneBusinessCompany;

namespace PackageBuilder.TestObjects.Mothers.DataProviderResponses.LightstoneAuto
{
    public class DirectorMother
    {
        public static IProvideDirector Director
        {
            get
            {
                return new DirectorBuilder()
                    .With(
                        1001,
                        1002,
                        1003,
                        "2010/018608/07",
                        "FirstName",
                        "Initials",
                        "Surname",
                        "SurnameParticular",
                        "PreviousSurname",
                        "IdNumber",
                        "BirthDate",
                        "DesignationCode",
                        "RsaResident",
                        "WithdrawPublic",
                        "CountryCode",
                        "TypeCode",
                        "StatusCode",
                        "StatusDate",
                        "RegisterNumber",
                        "ExecutorName",
                        "ExecutorAppointDate",
                        "TrusteeName",
                        "FormLodgeDate",
                        "FormReceiveDate",
                        "FoundingStatementDate",
                        10d,
                        11d,
                        "MemberContributionType",
                        1,
                        "OccupationCode",
                        "FineExpiryDate",
                        "NatureOfChange",
                        "NationalityCode",
                        "Profession",
                        "ResignationDate",
                        "Estate",
                        2, 
                        3
                    )
                    .With(
                    "BusinessAddress1", 
                    "BusinessAddress2", 
                    "BusinessAddress3", 
                    "BusinessAddress4", 
                    "BusinessPostCode",
                    "PostalAddress1", 
                    "PostalAddress2", 
                    "PostalAddress3", 
                    "PostalAddress4", 
                    "PostalPostCode",
                    "RegisteredAddress1", 
                    "RegisteredAddress2", 
                    "RegisteredAddress3", 
                    "RegisteredAddress4", 
                    "RegisteredPostCode",
                    "ResidentialAddress1", 
                    "ResidentialAddress2", 
                    "ResidentialAddress3", 
                    "ResidentialAddress4", 
                    "ResidentialPostCode"
                    )
                    .Build();
            }
        }
    }
}