//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lace.Source.Ivid.IvidServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ubiquitech.co.za/schemas/ivid/customTypes/", ConfigurationName="IvidServiceReference.HpiService")]
    public interface HpiService {
        
        // CODEGEN: Generating message contract since the operation HpiStandardQuery is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryResponse1 HpiStandardQuery(Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryResponse1> HpiStandardQueryAsync(Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ubiquitech.co.za/schemas/ivid/hpiService/")]
    public partial class HpiStandardQueryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hpiRequestReferenceField;
        
        private string applicantNameField;
        
        private string reasonForApplicationField;
        
        private string labelField;
        
        private string vinOrChassisField;
        
        private string engineNoField;
        
        private string registerNoField;
        
        private string licenceNoField;
        
        private string makeField;
        
        private RequesterDetailsElement requesterDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HpiRequestReference {
            get {
                return this.hpiRequestReferenceField;
            }
            set {
                this.hpiRequestReferenceField = value;
                this.RaisePropertyChanged("HpiRequestReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ApplicantName {
            get {
                return this.applicantNameField;
            }
            set {
                this.applicantNameField = value;
                this.RaisePropertyChanged("ApplicantName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReasonForApplication {
            get {
                return this.reasonForApplicationField;
            }
            set {
                this.reasonForApplicationField = value;
                this.RaisePropertyChanged("ReasonForApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("Label");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string VinOrChassis {
            get {
                return this.vinOrChassisField;
            }
            set {
                this.vinOrChassisField = value;
                this.RaisePropertyChanged("VinOrChassis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string EngineNo {
            get {
                return this.engineNoField;
            }
            set {
                this.engineNoField = value;
                this.RaisePropertyChanged("EngineNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RegisterNo {
            get {
                return this.registerNoField;
            }
            set {
                this.registerNoField = value;
                this.RaisePropertyChanged("RegisterNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LicenceNo {
            get {
                return this.licenceNoField;
            }
            set {
                this.licenceNoField = value;
                this.RaisePropertyChanged("LicenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
                this.RaisePropertyChanged("Make");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public RequesterDetailsElement requesterDetails {
            get {
                return this.requesterDetailsField;
            }
            set {
                this.requesterDetailsField = value;
                this.RaisePropertyChanged("requesterDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ubiquitech.co.za/schemas/ivid/customTypes/")]
    public partial class RequesterDetailsElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requesterNameField;
        
        private string requesterPhoneField;
        
        private string requesterEmailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string requesterName {
            get {
                return this.requesterNameField;
            }
            set {
                this.requesterNameField = value;
                this.RaisePropertyChanged("requesterName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string requesterPhone {
            get {
                return this.requesterPhoneField;
            }
            set {
                this.requesterPhoneField = value;
                this.RaisePropertyChanged("requesterPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string requesterEmail {
            get {
                return this.requesterEmailField;
            }
            set {
                this.requesterEmailField = value;
                this.RaisePropertyChanged("requesterEmail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ubiquitech.co.za/schemas/ivid/customTypes/")]
    public partial class CodeDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ubiquitech.co.za/schemas/ivid/customTypes/")]
    public partial class IssuesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool policeIssueField;
        
        private bool policeIssueFieldSpecified;
        
        private bool taxIssueField;
        
        private bool taxIssueFieldSpecified;
        
        private bool insuranceIssueField;
        
        private bool insuranceIssueFieldSpecified;
        
        private bool financingIssueField;
        
        private bool financingIssueFieldSpecified;
        
        private bool permitViolationIssueField;
        
        private bool permitViolationIssueFieldSpecified;
        
        private bool standardsIssueField;
        
        private bool standardsIssueFieldSpecified;
        
        private bool commercialIssueField;
        
        private bool commercialIssueFieldSpecified;
        
        private bool transportIssueField;
        
        private bool transportIssueFieldSpecified;
        
        private bool descriptionAbuseIssueField;
        
        private bool descriptionAbuseIssueFieldSpecified;
        
        private bool otherIssueField;
        
        private bool otherIssueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool PoliceIssue {
            get {
                return this.policeIssueField;
            }
            set {
                this.policeIssueField = value;
                this.RaisePropertyChanged("PoliceIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PoliceIssueSpecified {
            get {
                return this.policeIssueFieldSpecified;
            }
            set {
                this.policeIssueFieldSpecified = value;
                this.RaisePropertyChanged("PoliceIssueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool TaxIssue {
            get {
                return this.taxIssueField;
            }
            set {
                this.taxIssueField = value;
                this.RaisePropertyChanged("TaxIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxIssueSpecified {
            get {
                return this.taxIssueFieldSpecified;
            }
            set {
                this.taxIssueFieldSpecified = value;
                this.RaisePropertyChanged("TaxIssueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool InsuranceIssue {
            get {
                return this.insuranceIssueField;
            }
            set {
                this.insuranceIssueField = value;
                this.RaisePropertyChanged("InsuranceIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InsuranceIssueSpecified {
            get {
                return this.insuranceIssueFieldSpecified;
            }
            set {
                this.insuranceIssueFieldSpecified = value;
                this.RaisePropertyChanged("InsuranceIssueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool FinancingIssue {
            get {
                return this.financingIssueField;
            }
            set {
                this.financingIssueField = value;
                this.RaisePropertyChanged("FinancingIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FinancingIssueSpecified {
            get {
                return this.financingIssueFieldSpecified;
            }
            set {
                this.financingIssueFieldSpecified = value;
                this.RaisePropertyChanged("FinancingIssueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool PermitViolationIssue {
            get {
                return this.permitViolationIssueField;
            }
            set {
                this.permitViolationIssueField = value;
                this.RaisePropertyChanged("PermitViolationIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PermitViolationIssueSpecified {
            get {
                return this.permitViolationIssueFieldSpecified;
            }
            set {
                this.permitViolationIssueFieldSpecified = value;
                this.RaisePropertyChanged("PermitViolationIssueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool StandardsIssue {
            get {
                return this.standardsIssueField;
            }
            set {
                this.standardsIssueField = value;
                this.RaisePropertyChanged("StandardsIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StandardsIssueSpecified {
            get {
                return this.standardsIssueFieldSpecified;
            }
            set {
                this.standardsIssueFieldSpecified = value;
                this.RaisePropertyChanged("StandardsIssueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool CommercialIssue {
            get {
                return this.commercialIssueField;
            }
            set {
                this.commercialIssueField = value;
                this.RaisePropertyChanged("CommercialIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommercialIssueSpecified {
            get {
                return this.commercialIssueFieldSpecified;
            }
            set {
                this.commercialIssueFieldSpecified = value;
                this.RaisePropertyChanged("CommercialIssueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool TransportIssue {
            get {
                return this.transportIssueField;
            }
            set {
                this.transportIssueField = value;
                this.RaisePropertyChanged("TransportIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransportIssueSpecified {
            get {
                return this.transportIssueFieldSpecified;
            }
            set {
                this.transportIssueFieldSpecified = value;
                this.RaisePropertyChanged("TransportIssueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool DescriptionAbuseIssue {
            get {
                return this.descriptionAbuseIssueField;
            }
            set {
                this.descriptionAbuseIssueField = value;
                this.RaisePropertyChanged("DescriptionAbuseIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DescriptionAbuseIssueSpecified {
            get {
                return this.descriptionAbuseIssueFieldSpecified;
            }
            set {
                this.descriptionAbuseIssueFieldSpecified = value;
                this.RaisePropertyChanged("DescriptionAbuseIssueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool OtherIssue {
            get {
                return this.otherIssueField;
            }
            set {
                this.otherIssueField = value;
                this.RaisePropertyChanged("OtherIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OtherIssueSpecified {
            get {
                return this.otherIssueFieldSpecified;
            }
            set {
                this.otherIssueFieldSpecified = value;
                this.RaisePropertyChanged("OtherIssueSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ubiquitech.co.za/schemas/ivid/hpiService/")]
    public partial class HpiStandardQueryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IvidQueryResult ividQueryResultField;
        
        private IssuesType issuesTypesField;
        
        private string ividReferenceField;
        
        private bool partialResponseField;
        
        private bool partialResponseFieldSpecified;
        
        private string licenceNumberField;
        
        private string registerNumberField;
        
        private string vinField;
        
        private string engineNumberField;
        
        private string titleHolderIdNumberField;
        
        private IdType titleHolderIdTypeField;
        
        private bool titleHolderIdTypeFieldSpecified;
        
        private VehicleState vehicleStatusCodeField;
        
        private bool vehicleStatusCodeFieldSpecified;
        
        private string engineDisplacementField;
        
        private CodeDescription makeField;
        
        private CodeDescription modelField;
        
        private CodeDescription colourField;
        
        private CodeDescription drivenField;
        
        private string tareField;
        
        private string gVMField;
        
        private CodeDescription categoryField;
        
        private CodeDescription descriptionField;
        
        private CodeDescription economicSectorField;
        
        private CodeDescription lifeStatusField;
        
        private CodeDescription sapMarkField;
        
        private string registrationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IvidQueryResult ividQueryResult {
            get {
                return this.ividQueryResultField;
            }
            set {
                this.ividQueryResultField = value;
                this.RaisePropertyChanged("ividQueryResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IssuesType issuesTypes {
            get {
                return this.issuesTypesField;
            }
            set {
                this.issuesTypesField = value;
                this.RaisePropertyChanged("issuesTypes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IvidReference {
            get {
                return this.ividReferenceField;
            }
            set {
                this.ividReferenceField = value;
                this.RaisePropertyChanged("IvidReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool partialResponse {
            get {
                return this.partialResponseField;
            }
            set {
                this.partialResponseField = value;
                this.RaisePropertyChanged("partialResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool partialResponseSpecified {
            get {
                return this.partialResponseFieldSpecified;
            }
            set {
                this.partialResponseFieldSpecified = value;
                this.RaisePropertyChanged("partialResponseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string licenceNumber {
            get {
                return this.licenceNumberField;
            }
            set {
                this.licenceNumberField = value;
                this.RaisePropertyChanged("licenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string registerNumber {
            get {
                return this.registerNumberField;
            }
            set {
                this.registerNumberField = value;
                this.RaisePropertyChanged("registerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
                this.RaisePropertyChanged("vin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string engineNumber {
            get {
                return this.engineNumberField;
            }
            set {
                this.engineNumberField = value;
                this.RaisePropertyChanged("engineNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string titleHolderIdNumber {
            get {
                return this.titleHolderIdNumberField;
            }
            set {
                this.titleHolderIdNumberField = value;
                this.RaisePropertyChanged("titleHolderIdNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public IdType titleHolderIdType {
            get {
                return this.titleHolderIdTypeField;
            }
            set {
                this.titleHolderIdTypeField = value;
                this.RaisePropertyChanged("titleHolderIdType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool titleHolderIdTypeSpecified {
            get {
                return this.titleHolderIdTypeFieldSpecified;
            }
            set {
                this.titleHolderIdTypeFieldSpecified = value;
                this.RaisePropertyChanged("titleHolderIdTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public VehicleState vehicleStatusCode {
            get {
                return this.vehicleStatusCodeField;
            }
            set {
                this.vehicleStatusCodeField = value;
                this.RaisePropertyChanged("vehicleStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vehicleStatusCodeSpecified {
            get {
                return this.vehicleStatusCodeFieldSpecified;
            }
            set {
                this.vehicleStatusCodeFieldSpecified = value;
                this.RaisePropertyChanged("vehicleStatusCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string engineDisplacement {
            get {
                return this.engineDisplacementField;
            }
            set {
                this.engineDisplacementField = value;
                this.RaisePropertyChanged("engineDisplacement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public CodeDescription make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
                this.RaisePropertyChanged("make");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public CodeDescription model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public CodeDescription colour {
            get {
                return this.colourField;
            }
            set {
                this.colourField = value;
                this.RaisePropertyChanged("colour");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public CodeDescription driven {
            get {
                return this.drivenField;
            }
            set {
                this.drivenField = value;
                this.RaisePropertyChanged("driven");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string tare {
            get {
                return this.tareField;
            }
            set {
                this.tareField = value;
                this.RaisePropertyChanged("tare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string GVM {
            get {
                return this.gVMField;
            }
            set {
                this.gVMField = value;
                this.RaisePropertyChanged("GVM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public CodeDescription category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public CodeDescription description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public CodeDescription economicSector {
            get {
                return this.economicSectorField;
            }
            set {
                this.economicSectorField = value;
                this.RaisePropertyChanged("economicSector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public CodeDescription lifeStatus {
            get {
                return this.lifeStatusField;
            }
            set {
                this.lifeStatusField = value;
                this.RaisePropertyChanged("lifeStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public CodeDescription sapMark {
            get {
                return this.sapMarkField;
            }
            set {
                this.sapMarkField = value;
                this.RaisePropertyChanged("sapMark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string registrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
                this.RaisePropertyChanged("registrationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ubiquitech.co.za/schemas/ivid/customTypes/")]
    public enum IvidQueryResult {
        
        /// <remarks/>
        NO_RECORDS,
        
        /// <remarks/>
        NO_ISSUES,
        
        /// <remarks/>
        FURTHER_INVESTIGATION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ubiquitech.co.za/schemas/ivid/customTypes/")]
    public enum IdType {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        REG_NO_CERTIFICATE,
        
        /// <remarks/>
        RSA_ID_DOCUMENT,
        
        /// <remarks/>
        FOREIGN_ID_DOC,
        
        /// <remarks/>
        BUSINESS_REG_CERTIFICATE,
        
        /// <remarks/>
        FOREIGN_PASSPORT,
        
        /// <remarks/>
        ID_CARD,
        
        /// <remarks/>
        TRAVEL_DOCUMENT,
        
        /// <remarks/>
        FOREIGN_DRIVERS_LICENCE,
        
        /// <remarks/>
        SA_DRIVERS_LICENCE,
        
        /// <remarks/>
        SA_PASSPORT,
        
        /// <remarks/>
        REFERENCE_BOOK,
        
        /// <remarks/>
        TRANSVAAL_REG_NO,
        
        /// <remarks/>
        MERGED_ALIAS,
        
        /// <remarks/>
        PSEUDO_PERSON,
        
        /// <remarks/>
        OTHER,
        
        /// <remarks/>
        NONE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ubiquitech.co.za/schemas/ivid/customTypes/")]
    public enum VehicleState {
        
        /// <remarks/>
        INTRODUCED_BY_ONLINE_MIB_CONTROLLED,
        
        /// <remarks/>
        INTRODUCED_BY_ONLINE_MIB_RELEASED,
        
        /// <remarks/>
        INTRODUCED_BY_NON_MIB,
        
        /// <remarks/>
        INTRODUCED_BY_POLICE_PRIVATE_OR_BUSINESS,
        
        /// <remarks/>
        REGISTERED_EXEMPT_FROM_LICENSING,
        
        /// <remarks/>
        REGISTERED_LIABLE_FOR_LICENSING,
        
        /// <remarks/>
        REGISTERED_EXEMPT_AND_LIMITED_OWNER,
        
        /// <remarks/>
        DEREGISTERED_BY_REQUEST,
        
        /// <remarks/>
        DEREGISTERED_BY_DEFAULT,
        
        /// <remarks/>
        EXPORTED_WHILE_EXEMPT_FROM_LICENSING,
        
        /// <remarks/>
        EXPORTED_WHILE_LICENSED,
        
        /// <remarks/>
        LICENSED,
        
        /// <remarks/>
        UNLICENSED_LIABLE_FOR_LICENSING,
        
        /// <remarks/>
        PENDING_SALE_FROM_MD_TO_MD,
        
        /// <remarks/>
        PENDING_SALE_FROM_MIB_MD_TO_PERSON,
        
        /// <remarks/>
        PENDING_NOTIFIED_OF_STOLEN_SCRAPPED,
        
        /// <remarks/>
        PENDING_TRANSFER_TO_LIMITED_OWNER,
        
        /// <remarks/>
        PENDING_SALE_OF_USED_MV,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HpiStandardQueryRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ubiquitech.co.za/schemas/ivid/hpiService/", Order=0)]
        public Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryRequest HpiStandardQueryRequest;
        
        public HpiStandardQueryRequest1() {
        }
        
        public HpiStandardQueryRequest1(Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryRequest HpiStandardQueryRequest) {
            this.HpiStandardQueryRequest = HpiStandardQueryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HpiStandardQueryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ubiquitech.co.za/schemas/ivid/hpiService/", Order=0)]
        public Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryResponse HpiStandardQueryResponse;
        
        public HpiStandardQueryResponse1() {
        }
        
        public HpiStandardQueryResponse1(Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryResponse HpiStandardQueryResponse) {
            this.HpiStandardQueryResponse = HpiStandardQueryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HpiServiceChannel : Lace.Source.Ivid.IvidServiceReference.HpiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HpiServiceClient : System.ServiceModel.ClientBase<Lace.Source.Ivid.IvidServiceReference.HpiService>, Lace.Source.Ivid.IvidServiceReference.HpiService {
        
        public HpiServiceClient() {
        }
        
        public HpiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HpiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HpiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HpiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryResponse1 Lace.Source.Ivid.IvidServiceReference.HpiService.HpiStandardQuery(Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryRequest1 request) {
            return base.Channel.HpiStandardQuery(request);
        }
        
        public Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryResponse HpiStandardQuery(Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryRequest HpiStandardQueryRequest) {
            Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryRequest1 inValue = new Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryRequest1();
            inValue.HpiStandardQueryRequest = HpiStandardQueryRequest;
            Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryResponse1 retVal = ((Lace.Source.Ivid.IvidServiceReference.HpiService)(this)).HpiStandardQuery(inValue);
            return retVal.HpiStandardQueryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryResponse1> Lace.Source.Ivid.IvidServiceReference.HpiService.HpiStandardQueryAsync(Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryRequest1 request) {
            return base.Channel.HpiStandardQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryResponse1> HpiStandardQueryAsync(Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryRequest HpiStandardQueryRequest) {
            Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryRequest1 inValue = new Lace.Source.Ivid.IvidServiceReference.HpiStandardQueryRequest1();
            inValue.HpiStandardQueryRequest = HpiStandardQueryRequest;
            return ((Lace.Source.Ivid.IvidServiceReference.HpiService)(this)).HpiStandardQueryAsync(inValue);
        }
    }
}
